# -*- coding: utf-8 -*-
"""自动生成：ACM Workflow 知识导论数据（独立版）。"""

from info_framework import get_alg_info

ALGORITHMS = [
    {
        'category': '基础算法',
        'sub': '枚举',
        'name': '暴力枚举',
            'quality': 'complete',
        'aliases': ['枚举', 'brute force'],
        'intro': '数据范围小或答案空间有限时，直接枚举所有情况并验证。模板：枚举所有子区间求最大子段和。',
        'complexity': 'O(n²)（本例）',
        'cpp': 'int maxSubarray(const vector<int>& a) {\n  int n = (int)a.size(), ans = INT_MIN;\n  for (int l = 0; l < n; l++) {\n    int s = 0;\n    for (int r = l; r < n; r++) {\n      s += a[r];\n      ans = max(ans, s);\n    }\n  }\n  return ans;\n}',
    },
    {
        'category': '基础算法',
        'sub': '模拟',
        'name': '约瑟夫环（模拟）',
            'quality': 'complete',
        'aliases': ['约瑟夫问题', 'simulation'],
        'intro': 'n 个人围成一圈报数，每数到 k 出列。直接用 vector 模拟删除过程。',
        'complexity': 'O(nk)',
        'cpp': 'int josephus(int n, int k) {\n  vector<int> v(n);\n  iota(v.begin(), v.end(), 1);\n  int idx = 0;\n  while (v.size() > 1) {\n    idx = (idx + k - 1) % (int)v.size();\n    v.erase(v.begin() + idx);\n  }\n  return v[0];\n}',
    },
    {
        'category': '基础算法',
        'sub': '贪心',
        'name': '区间调度（贪心）',
            'quality': 'complete',
        'aliases': ['贪心', 'greedy', '区间选点'],
        'intro': '选择尽量多的互不相交区间：按右端点升序，能取就取。',
        'complexity': 'O(n log n)（排序）',
        'cpp': 'int intervalSchedule(vector<pair<int,int>>& seg) {\n  sort(seg.begin(), seg.end(),\n       [](auto& a, auto& b) { return a.second < b.second; });\n  int cnt = 0, last = INT_MIN;\n  for (auto [l, r] : seg)\n    if (l > last) { cnt++; last = r; }\n  return cnt;\n}',
    },
    {
        'category': '基础算法',
        'sub': '贪心',
        'name': '排序后取最值（基础贪心）',
            'quality': 'complete',
        'aliases': ['基础贪心', 'sortings + greedy', '排序贪心'],
        'intro': '先按某个关键字排序，再顺序取当前最优值；适用于排序后直接选最大/最小的基础贪心。',
        'complexity': 'O(n log n)（排序）',
        'cpp': 'long long maxAfterSort(vector<int>& profits, int k) {\n  sort(profits.rbegin(), profits.rend());\n  long long ans = 0;\n  for (int i = 0; i < k && i < (int)profits.size(); i++) ans += profits[i];\n  return ans;\n}',
    },
    {
        'category': '基础算法',
        'sub': '贪心',
        'name': '反悔贪心（带堆维护）',
            'quality': 'complete',
        'aliases': ['反悔贪心', '后悔堆', 'matroids / greedy'],
        'intro': '当前贪心选择可能被更优解替换，用小根堆维护已选集合中“反悔代价最小”的元素。',
        'complexity': 'O(n log n)',
        'cpp': 'long long regretGreedy(vector<pair<int,int>>& a) {\n  // 例：每个任务耗时 1，求在截止时间限制内的最大价值\n  sort(a.begin(), a.end()); // 按截止时间排序\n  priority_queue<int, vector<int>, greater<int>> pq;\n  long long sum = 0;\n  for (auto& [d, v] : a) {\n    pq.push(v); sum += v;\n    if ((int)pq.size() > d) { sum -= pq.top(); pq.pop(); }\n  }\n  return sum;\n}',
    },
    {
        'category': '基础算法',
        'sub': '二分',
        'name': '二分查找',
            'quality': 'complete',
        'aliases': ['二分', 'binary search'],
        'intro': '有序数组折半查找目标；`l + (r - l) / 2` 防溢出。',
        'complexity': 'O(log n)',
        'cpp': 'int binarySearch(const vector<int>& a, int target) {\n  int l = 0, r = (int)a.size() - 1;\n  while (l <= r) {\n    int m = l + (r - l) / 2;\n    if (a[m] == target) return m;\n    if (a[m] < target) l = m + 1; else r = m - 1;\n  }\n  return -1;\n}',
    },
    {
        'category': '基础算法',
        'sub': '二分',
        'name': '二分答案',
            'quality': 'complete',
        'aliases': ['二分答案', '最大化最小值', '最小化最大值'],
        'intro': '答案具有单调性时，直接二分答案并 O(n) 验证；check 随题目实现。',
        'complexity': 'O(n log V)（V 为答案值域）',
        'cpp': 'bool check(long long x); // 按题目实现：x 是否可行\n\nlong long binaryAnswer() {\n  long long lo = 0, hi = 1e18, ans = hi;\n  while (lo <= hi) {\n    long long mid = (lo + hi) / 2;\n    if (check(mid)) { ans = mid; hi = mid - 1; }\n    else lo = mid + 1;\n  }\n  return ans;\n}',
    },
    {
        'category': '基础算法',
        'sub': '分治',
        'name': '归并排序求逆序对',
            'quality': 'complete',
        'aliases': ['分治', '逆序对', 'merge sort'],
        'intro': '经典分治：左半与右半分别有序后，统计跨左右逆序对并归并。',
        'complexity': 'O(n log n)',
        'cpp': 'long long mergeSort(vector<int>& a, int l, int r) {\n  if (l >= r) return 0;\n  int m = (l + r) / 2;\n  long long cnt = mergeSort(a, l, m) + mergeSort(a, m + 1, r);\n  vector<int> t;\n  int i = l, j = m + 1;\n  while (i <= m && j <= r) {\n    if (a[i] <= a[j]) t.push_back(a[i++]);\n    else { t.push_back(a[j++]); cnt += m - i + 1; }\n  }\n  while (i <= m) t.push_back(a[i++]);\n  while (j <= r) t.push_back(a[j++]);\n  for (int k = 0; k < (int)t.size(); k++) a[l + k] = t[k];\n  return cnt;\n}',
    },
    {
        'category': '基础算法',
        'sub': '排序',
        'name': '结构体排序（重载运算符）',
            'quality': 'complete',
        'aliases': ['排序', 'sort', 'sortings', '重载运算符'],
        'intro': '自定义结构体排序：重载 < 运算符或传入比较函数，按多关键字排序。',
        'complexity': 'O(n log n)',
        'cpp': 'struct Node { int a, b; };\nbool cmp(const Node& x, const Node& y) {\n  if (x.a != y.a) return x.a < y.a;\n  return x.b < y.b;\n}\n// sort(v.begin(), v.end(), cmp);',
    },
    {
        'category': '基础算法',
        'sub': '前缀和与差分',
        'name': '一维前缀和',
            'quality': 'complete',
        'aliases': ['前缀和', 'prefix sum', '一维前缀和'],
        'intro': '预处理前缀和数组，O(1) 求任意区间 [l,r] 的和。',
        'complexity': 'O(n) 预处理 / O(1) 查询',
        'cpp': 'vector<long long> pre(n + 1);\nfor (int i = 0; i < n; i++) pre[i+1] = pre[i] + a[i];\n// sum(l, r) = pre[r+1] - pre[l]',
    },
    {
        'category': '基础算法',
        'sub': '前缀和与差分',
        'name': '二维前缀和',
            'quality': 'complete',
        'aliases': ['二维前缀和', '2D prefix sum'],
        'intro': '用容斥预处理二维前缀和，O(1) 求子矩阵和。',
        'complexity': 'O(nm) 预处理 / O(1) 查询',
        'cpp': 'vector<vector<long long>> s(n+1, vector<long long>(m+1));\nfor (int i=1;i<=n;i++)\n  for (int j=1;j<=m;j++)\n    s[i][j]=s[i-1][j]+s[i][j-1]-s[i-1][j-1]+a[i-1][j-1];\n// sum(x1,y1,x2,y2) = s[x2][y2]-s[x1-1][y2]-s[x2][y1-1]+s[x1-1][y1-1]',
    },
    {
        'category': '基础算法',
        'sub': '前缀和与差分',
        'name': '差分数组',
            'quality': 'complete',
        'aliases': ['差分', 'difference array'],
        'intro': '区间加 O(1) 更新，最后求前缀和还原原数组。',
        'complexity': 'O(n+q)',
        'cpp': 'vector<long long> diff(n+2);\n// 区间 [l,r] 加 v：diff[l]+=v; diff[r+1]-=v;\nfor (int i=1;i<=n;i++) diff[i]+=diff[i-1]; // 还原',
    },
    {
        'category': '基础算法',
        'sub': '双指针',
        'name': '双指针（滑动窗口）',
            'quality': 'complete',
        'aliases': ['双指针', 'two pointers', '滑动窗口'],
        'intro': '维护左右端点，窗口满足条件时移动左端并更新答案，常用于子数组/子串问题。',
        'complexity': 'O(n)',
        'cpp': 'int slidingWindow(vector<int>& a, int k) {\n  int n=a.size(), l=0, sum=0, ans=0;\n  for (int r=0; r<n; r++) {\n    sum += a[r];\n    while (sum > k) sum -= a[l++];\n    ans = max(ans, r-l+1);\n  }\n  return ans;\n}',
    },
    {
        'category': '基础算法',
        'sub': '构造',
        'name': '构造算法',
            'quality': 'complete',
        'aliases': ['构造', 'constructive algorithms'],
        'intro': '利用奇偶性、模运算或特殊性质直接构造一组满足条件的解。',
        'complexity': 'O(n) 或 O(1)（视题目）',
        'cpp': 'vector<int> construct(int n) {\n  vector<int> ans(n);\n  for (int i=0;i<n;i++) ans[i] = (i%2==0 ? i/2+1 : n-i/2); // 示例：奇偶构造\n  return ans;\n}',
    },
    {
        'category': '基础算法',
        'sub': '位运算',
        'name': '位掩码子集枚举',
            'quality': 'complete',
        'aliases': ['位掩码', '子集枚举', 'bitmasks', 'subset'],
        'intro': '枚举 mask 的所有非空子集，常用 sub=(sub-1)&mask 跳过无效状态。',
        'complexity': 'O(3^n)（所有子集的子集）',
        'cpp': 'for (int sub = mask; ; sub = (sub - 1) & mask) {\n  // 处理 sub\n  if (sub == 0) break;\n}',
    },
    {
        'category': '基础算法',
        'sub': '位运算',
        'name': '状态压缩 + BFS',
            'quality': 'complete',
        'aliases': ['状压 BFS', 'bitmask bfs'],
        'intro': '把状态压缩成二进制，BFS 求最短步数；常用于小规模地图/钥匙问题。',
        'complexity': 'O(状态数 × 转移)',
        'cpp': '// dist[mask][pos] 初始 -1，BFS 队列 (mask,pos)\nqueue<pair<int,int>> q;\ndist[startMask][start] = 0; q.push({startMask, start});\nwhile (!q.empty()) {\n  auto [mask,u] = q.front(); q.pop();\n  for (int v : g[u]) {\n    int nm = mask | key[v];\n    if (dist[nm][v] == -1) { dist[nm][v] = dist[mask][u]+1; q.push({nm,v}); }\n  }\n}',
    },
    {
        'category': '数据结构',
        'sub': '栈',
        'name': '单调栈',
            'quality': 'complete',
        'aliases': ['栈', 'next greater', '下一个更大元素'],
        'intro': '维护单调递减栈，O(n) 求每个元素右侧第一个更大元素（存下标）。',
        'complexity': 'O(n)',
        'cpp': 'vector<int> nextGreater(const vector<int>& a) {\n  int n = (int)a.size();\n  vector<int> res(n, -1);\n  stack<int> st; // 存下标，栈内值单调递减\n  for (int i = 0; i < n; i++) {\n    while (!st.empty() && a[st.top()] < a[i]) {\n      res[st.top()] = a[i];\n      st.pop();\n    }\n    st.push(i);\n  }\n  return res;\n}',
    },
    {
        'category': '数据结构',
        'sub': '栈',
        'name': '栈（基础）',
            'quality': 'complete',
        'aliases': ['栈', 'stack'],
        'intro': '后进先出，常用 vector 模拟；典型应用括号匹配、表达式求值。',
        'complexity': 'O(1) 入栈/出栈',
        'cpp': 'vector<int> st;\nst.push_back(x); // 入栈\nint top = st.back();\nst.pop_back();   // 出栈',
    },
    {
        'category': '数据结构',
        'sub': '队列',
        'name': '单调队列（滑动窗口）',
            'quality': 'complete',
        'aliases': ['队列', '滑动窗口', 'deque'],
        'intro': '窗口滑过数组，队头为窗口最大值；过期下标从队头弹出。',
        'complexity': 'O(n)',
        'cpp': 'vector<int> maxSlidingWindow(const vector<int>& a, int k) {\n  deque<int> q; // 存下标，值单调递减\n  vector<int> res;\n  for (int i = 0; i < (int)a.size(); i++) {\n    while (!q.empty() && a[q.back()] <= a[i]) q.pop_back();\n    q.push_back(i);\n    if (q.front() <= i - k) q.pop_front();   // 过期\n    if (i >= k - 1) res.push_back(a[q.front()]);\n  }\n  return res;\n}',
    },
    {
        'category': '数据结构',
        'sub': '队列',
        'name': '队列（基础）',
            'quality': 'complete',
        'aliases': ['队列', 'queue'],
        'intro': '先进先出，BFS 与拓扑排序的基础容器。',
        'complexity': 'O(1) 入队/出队',
        'cpp': 'queue<int> q;\nq.push(x);\nint front = q.front();\nq.pop();',
    },
    {
        'category': '数据结构',
        'sub': '堆',
        'name': '堆（Top-K）',
            'quality': 'complete',
        'aliases': ['堆', '优先队列', 'priority queue'],
        'intro': '小根堆维护前 K 大：比堆顶大就替换，堆内即答案。',
        'complexity': 'O(n log k)',
        'cpp': 'vector<int> topK(vector<int> a, int k) {\n  priority_queue<int, vector<int>, greater<int>> pq;\n  for (int x : a) {\n    pq.push(x);\n    if ((int)pq.size() > k) pq.pop();\n  }\n  vector<int> res;\n  while (!pq.empty()) { res.push_back(pq.top()); pq.pop(); }\n  return res;\n}',
    },
    {
        'category': '数据结构',
        'sub': '并查集',
        'name': '并查集 (DSU)',
            'quality': 'complete',
        'aliases': ['union find', 'disjoint set'],
        'intro': '近似 O(1) 的合并/查找；路径压缩 + 按秩合并保证摊还复杂度。',
        'complexity': 'O(α(n)) 摊还',
        'cpp': 'struct DSU {\n  vector<int> p, sz;\n  DSU(int n) : p(n), sz(n, 1) { iota(p.begin(), p.end(), 0); }\n  int find(int x) { return p[x] == x ? x : p[x] = find(p[x]); }\n  void unite(int a, int b) {\n    a = find(a); b = find(b);\n    if (a == b) return;\n    if (sz[a] < sz[b]) swap(a, b);\n    p[b] = a; sz[a] += sz[b];\n  }\n  bool same(int a, int b) { return find(a) == find(b); }\n};',
    },
    {
        'category': '数据结构',
        'sub': '并查集',
        'name': '带权并查集',
            'quality': 'complete',
        'aliases': ['带权并查集', 'weighted dsu'],
        'intro': '在路径压缩时维护每个点到根的距离/权值，可处理“相对关系”问题。',
        'complexity': 'O(α(n)) 摊还',
        'cpp': 'struct DSU {\n  vector<int> p, sz, w; // w[x] 表示 x 到 p[x] 的权值\n  DSU(int n): p(n), sz(n,1), w(n,0) { iota(p.begin(), p.end(), 0); }\n  int find(int x) {\n    if (p[x] == x) return x;\n    int root = find(p[x]);\n    w[x] += w[p[x]];\n    return p[x] = root;\n  }\n  // unite 时按需更新 w\n};',
    },
    {
        'category': '数据结构',
        'sub': '线段树',
        'name': '线段树（区间和 + 懒标记）',
            'quality': 'complete',
        'aliases': ['segment tree', '懒标记'],
        'intro': '四倍空间存区间和与懒标记；区间加、区间求和均 O(log n)。',
        'complexity': 'O(log n) 每次操作',
        'cpp': 'struct SegTree {\n  int n; vector<long long> sum, lazy;\n  SegTree(int n) : n(n), sum(4 * n), lazy(4 * n) {}\n  void apply(int p, long long v, int len) { sum[p] += v * len; lazy[p] += v; }\n  void push(int p, int l, int r) {\n    if (lazy[p] && l != r) {\n      int m = (l + r) / 2;\n      apply(p*2, lazy[p], m - l + 1);\n      apply(p*2+1, lazy[p], r - m);\n      lazy[p] = 0;\n    }\n  }\n  void add(int p, int l, int r, int ql, int qr, long long v) {\n    if (ql <= l && r <= qr) { apply(p, v, r - l + 1); return; }\n    push(p, l, r);\n    int m = (l + r) / 2;\n    if (ql <= m) add(p*2, l, m, ql, qr, v);\n    if (qr > m) add(p*2+1, m+1, r, ql, qr, v);\n    sum[p] = sum[p*2] + sum[p*2+1];\n  }\n  long long query(int p, int l, int r, int ql, int qr) {\n    if (ql <= l && r <= qr) return sum[p];\n    push(p, l, r);\n    int m = (l + r) / 2; long long res = 0;\n    if (ql <= m) res += query(p*2, l, m, ql, qr);\n    if (qr > m) res += query(p*2+1, m+1, r, ql, qr);\n    return res;\n  }\n};',
    },
    {
        'category': '数据结构',
        'sub': '线段树',
        'name': 'ST 表（静态区间最值）',
            'quality': 'complete',
        'aliases': ['RMQ', '稀疏表', 'sparse table'],
        'intro': '预处理 2^k 区间最值，O(1) 回答静态区间最小值；不可修改。',
        'complexity': 'O(n log n) 预处理 / O(1) 查询',
        'cpp': 'struct SparseTable {\n  int n, K;\n  vector<vector<long long>> st;\n  SparseTable(const vector<long long>& a) : n(a.size()) {\n    K = 32 - __builtin_clz(n);\n    st.assign(K, vector<long long>(n));\n    st[0] = a;\n    for (int k = 1; k < K; k++)\n      for (int i = 0; i + (1 << k) <= n; i++)\n        st[k][i] = min(st[k-1][i], st[k-1][i + (1 << (k-1))]);\n  }\n  long long query(int l, int r) {  // [l, r] 最小值\n    int k = 31 - __builtin_clz(r - l + 1);\n    return min(st[k][l], st[k][r - (1 << k) + 1]);\n  }\n};',
    },
    {
        'category': '数据结构',
        'sub': '树状数组',
        'name': '树状数组 (BIT)',
            'quality': 'complete',
        'aliases': ['Fenwick', 'binary indexed tree'],
        'intro': '单点修改 + 前缀和查询，常数极小；区间和 = 两次前缀和之差。',
        'complexity': 'O(log n) 每次操作',
        'cpp': 'struct Fenwick {\n  int n; vector<long long> bit;\n  Fenwick(int n) : n(n), bit(n + 1) {}\n  void add(int i, long long v) { for (; i <= n; i += i & -i) bit[i] += v; }\n  long long sum(int i) {\n    long long r = 0;\n    for (; i > 0; i -= i & -i) r += bit[i];\n    return r;\n  }\n  long long range(int l, int r) { return sum(r) - sum(l - 1); }\n};',
    },
    {
        'category': '数据结构',
        'sub': '树状数组',
        'name': '树状数组求逆序对',
            'quality': 'complete',
        'aliases': ['逆序对', 'BIT 逆序对'],
        'intro': '离散化后按值域插入 BIT，统计已插入且大于当前数的个数。',
        'complexity': 'O(n log n)',
        'cpp': 'long long inversionCount(vector<int>& a) {\n  vector<int> v=a; sort(v.begin(), v.end());\n  v.erase(unique(v.begin(), v.end()), v.end());\n  Fenwick bit(v.size());\n  long long ans=0;\n  for (int x : a) {\n    int id = lower_bound(v.begin(), v.end(), x)-v.begin()+1;\n    ans += bit.sum(v.size()) - bit.sum(id);\n    bit.add(id, 1);\n  }\n  return ans;\n}',
    },
    {
        'category': '数据结构',
        'sub': '高级数据结构',
        'name': 'FHQ Treap（无旋 Treap）',
            'quality': 'complete',
        'aliases': ['FHQ Treap', '无旋 Treap', 'treap'],
        'intro': '用 split/merge 实现插入、删除、区间翻转与第 k 大，无需旋转。',
        'complexity': 'O(log n) 期望',
        'cpp': 'struct Node { int l=0,r=0,sz=1,pri=rand(); long long val; };\nvector<Node> t(1);\nint newNode(long long v){ t.push_back({0,0,1,rand(),v}); return t.size()-1; }\nvoid pushup(int x){ t[x].sz=t[t[x].l].sz+t[t[x].r].sz+1; }\nvoid split(int x,int k,int& a,int& b){\n  if(!x){a=b=0;return;}\n  if(t[t[x].l].sz>=k){ split(t[x].l,k,a,t[x].l); b=x; pushup(b); }\n  else { split(t[x].r,k-t[t[x].l].sz-1,t[x].r,b); a=x; pushup(a); }\n}\nint merge(int a,int b){\n  if(!a||!b) return a?a:b;\n  if(t[a].pri<t[b].pri){ t[a].r=merge(t[a].r,b); pushup(a); return a;}\n  else {t[b].l=merge(a,t[b].l); pushup(b); return b;}\n}',
    },
    {
        'category': '数据结构',
        'sub': '高级数据结构',
        'name': '线段树合并/分裂',
            'quality': 'complete',
        'aliases': ['线段树合并', '线段树分裂'],
        'intro': '动态开点线段树，合并两棵树或按权值分裂，用于树上颜色计数、区间排序等。',
        'complexity': 'O(n log V) 总合并',
        'cpp': 'int merge(int a,int b){\n  if(!a||!b) return a?a:b;\n  sum[a]+=sum[b];\n  lc[a]=merge(lc[a],lc[b]);\n  rc[a]=merge(rc[a],rc[b]);\n  return a;\n}',
    },
    {
        'category': '数据结构',
        'sub': '高级数据结构',
        'name': '可撤销并查集',
            'quality': 'complete',
        'aliases': ['可撤销并查集', 'rollback dsu'],
        'intro': '按秩合并 + 用栈记录每次修改，支持回滚到历史版本，配合线段树分治。',
        'complexity': 'O(log n) 摊还',
        'cpp': 'struct DSU {\n  vector<int> p, sz;\n  vector<tuple<int,int,int,int>> hist;\n  int find(int x){ while(p[x]!=x) x=p[x]; return x; }\n  bool unite(int a,int b){\n    a=find(a); b=find(b);\n    if(a==b) return false;\n    if(sz[a]<sz[b]) swap(a,b);\n    hist.push_back({a,b,sz[a],sz[b]});\n    p[b]=a; sz[a]+=sz[b]; return true;\n  }\n  void rollback(){ auto [a,b,sa,sb]=hist.back(); hist.pop_back(); p[b]=b; sz[a]=sa; sz[b]=sb; }\n};',
    },
    {
        'category': '图论',
        'sub': '最短路',
        'name': 'Dijkstra',
            'quality': 'complete',
        'aliases': ['迪杰斯特拉', '单源最短路'],
        'intro': '非负权图单源最短路；优先队列取当前最近点，松弛邻边。',
        'complexity': 'O((V+E) log V)',
        'cpp': 'vector<long long> dijkstra(int s, const vector<vector<pair<int,int>>>& g) {\n  int n = g.size();\n  vector<long long> d(n, LLONG_MAX);\n  priority_queue<pair<long long,int>, vector<pair<long long,int>>, greater<>> pq;\n  d[s] = 0; pq.push({0, s});\n  while (!pq.empty()) {\n    auto [du, u] = pq.top(); pq.pop();\n    if (du > d[u]) continue;\n    for (auto [v, w] : g[u])\n      if (d[u] + w < d[v]) { d[v] = d[u] + w; pq.push({d[v], v}); }\n  }\n  return d;\n}',
    },
    {
        'category': '图论',
        'sub': '最短路',
        'name': 'Bellman-Ford',
            'quality': 'complete',
        'aliases': ['贝尔曼福特', '负权边', '负环'],
        'intro': '可处理负权边，并检测负环：第 n 轮仍能松弛说明存在负环。',
        'complexity': 'O(V·E)',
        'cpp': 'bool bellmanFord(int s, int n, const vector<array<int,3>>& e, vector<long long>& d) {\n  d.assign(n, LLONG_MAX); d[s] = 0;\n  for (int i = 0; i < n - 1; i++) {\n    bool changed = false;\n    for (auto [u, v, w] : e)\n      if (d[u] != LLONG_MAX && d[u] + w < d[v]) { d[v] = d[u] + w; changed = true; }\n    if (!changed) break;\n  }\n  for (auto [u, v, w] : e)\n    if (d[u] != LLONG_MAX && d[u] + w < d[v]) return false;  // 有负环\n  return true;\n}',
    },
    {
        'category': '图论',
        'sub': '最短路',
        'name': 'Floyd-Warshall',
            'quality': 'complete',
        'aliases': ['弗洛伊德', '全源最短路'],
        'intro': '全源最短路，三重循环枚举中转点；负权可行（无负环）。',
        'complexity': 'O(V³)',
        'cpp': 'void floyd(vector<vector<long long>>& d) {\n  int n = d.size();\n  for (int k = 0; k < n; k++)\n    for (int i = 0; i < n; i++)\n      for (int j = 0; j < n; j++)\n        if (d[i][k] != LLONG_MAX && d[k][j] != LLONG_MAX)\n          d[i][j] = min(d[i][j], d[i][k] + d[k][j]);\n}',
    },
    {
        'category': '图论',
        'sub': '最小生成树',
        'name': 'Kruskal',
            'quality': 'complete',
        'aliases': ['克鲁斯卡尔', 'MST', '最小生成树'],
        'intro': '按边权升序加入，并查集判环；边少（稀疏图）时优先。',
        'complexity': 'O(E log E)',
        'cpp': 'struct DSU {\n  vector<int> p, sz;\n  DSU(int n) : p(n), sz(n, 1) { iota(p.begin(), p.end(), 0); }\n  int find(int x) { return p[x] == x ? x : p[x] = find(p[x]); }\n  bool unite(int a, int b) {\n    a = find(a); b = find(b);\n    if (a == b) return false;\n    if (sz[a] < sz[b]) swap(a, b);\n    p[b] = a; sz[a] += sz[b]; return true;\n  }\n};\nlong long kruskal(int n, vector<array<int,3>>& edges) {\n  sort(edges.begin(), edges.end(), [](auto& x, auto& y){ return x[2] < y[2]; });\n  DSU dsu(n); long long cost = 0;\n  for (auto [u, v, w] : edges)\n    if (dsu.unite(u, v)) cost += w;\n  return cost;\n}',
    },
    {
        'category': '图论',
        'sub': '最小生成树',
        'name': 'Prim',
            'quality': 'complete',
        'aliases': ['Prim', '普里姆', '最小生成树'],
        'intro': '从任意点开始，每次选连接已选集合的最小边；稠密图用邻接矩阵/堆优化。',
        'complexity': 'O(n²) 朴素 / O((n+m) log n) 堆优化',
        'cpp': 'long long prim(int n, vector<vector<pair<int,int>>>& g) {\n  const long long INF=1e18;\n  vector<long long> d(n, INF); vector<char> used(n);\n  d[0]=0; long long ans=0;\n  for(int i=0;i<n;i++){\n    int u=-1;\n    for(int v=0;v<n;v++) if(!used[v] && (u==-1 || d[v]<d[u])) u=v;\n    if(d[u]==INF) return -1;\n    used[u]=1; ans+=d[u];\n    for(auto [v,w]:g[u]) d[v]=min(d[v],(long long)w);\n  }\n  return ans;\n}',
    },
    {
        'category': '图论',
        'sub': '网络流',
        'name': 'Dinic 最大流',
            'quality': 'complete',
        'aliases': ['网络流', 'max flow', 'ISAP 替代'],
        'intro': 'BFS 分层 + DFS 多路增广（当前弧优化），最坏 O(V²E)，实际飞快。',
        'complexity': 'O(V²E)',
        'cpp': 'struct Dinic {\n  struct Edge { int to, rev; long long cap; };\n  vector<vector<Edge>> g; vector<int> level, it;\n  Dinic(int n) : g(n), level(n), it(n) {}\n  void add(int u, int v, long long c) {\n    g[u].push_back({v, (int)g[v].size(), c});\n    g[v].push_back({u, (int)g[u].size() - 1, 0});\n  }\n  bool bfs(int s, int t) {\n    fill(level.begin(), level.end(), -1);\n    queue<int> q; level[s] = 0; q.push(s);\n    while (!q.empty()) {\n      int u = q.front(); q.pop();\n      for (auto& e : g[u])\n        if (e.cap > 0 && level[e.to] < 0) {\n          level[e.to] = level[u] + 1; q.push(e.to);\n        }\n    }\n    return level[t] >= 0;\n  }\n  long long dfs(int u, int t, long long f) {\n    if (u == t) return f;\n    for (int& i = it[u]; i < (int)g[u].size(); i++) {\n      auto& e = g[u][i];\n      if (e.cap > 0 && level[e.to] == level[u] + 1) {\n        long long d = dfs(e.to, t, min(f, e.cap));\n        if (d > 0) { e.cap -= d; g[e.to][e.rev].cap += d; return d; }\n      }\n    }\n    return 0;\n  }\n  long long maxFlow(int s, int t) {\n    long long flow = 0;\n    while (bfs(s, t)) {\n      fill(it.begin(), it.end(), 0);\n      while (long long d = dfs(s, t, LLONG_MAX)) flow += d;\n    }\n    return flow;\n  }\n};',
    },
    {
        'category': '图论',
        'sub': '网络流',
        'name': '最小割建模',
            'quality': 'complete',
        'aliases': ['最小割', 'min cut', '最大权闭合子图'],
        'intro': '最大流 = 最小割；把收益/代价连到源/汇，割的代价对应答案。',
        'complexity': 'O(Dinic)',
        'cpp': 'void buildMaxClosure(int n, vector<long long>& w, vector<pair<int,int>>& edges) {\n  Dinic din(n + 2);\n  int S = n, T = n + 1;\n  long long sum = 0;\n  for (int i = 0; i < n; i++) {\n    if (w[i] > 0) { din.add(S, i, w[i]); sum += w[i]; }\n    else if (w[i] < 0) din.add(i, T, -w[i]);\n  }\n  for (auto [u, v] : edges) din.add(u, v, LLONG_MAX);\n  // 最大权闭合子图 = sum - din.maxFlow(S, T)\n}',
    },
    {
        'category': '图论',
        'sub': '强连通分量',
        'name': 'Tarjan 求 SCC',
            'quality': 'complete',
        'aliases': ['强连通分量', '缩点', 'scc', 'tarjan'],
        'intro': 'low 值与 dfn 相等即找到一个强连通分量；缩点后图是 DAG。',
        'complexity': 'O(V+E)',
        'cpp': 'struct SCC {\n  int n, timer = 0, cnt = 0;\n  vector<vector<int>> g;\n  vector<int> dfn, low, belong;\n  vector<int> stk; vector<char> inStk;\n  SCC(int n, const vector<vector<int>>& g)\n    : n(n), g(g), dfn(n), low(n), belong(n), inStk(n) {}\n  void dfs(int u) {\n    dfn[u] = low[u] = ++timer;\n    stk.push_back(u); inStk[u] = 1;\n    for (int v : g[u]) {\n      if (!dfn[v]) { dfs(v); low[u] = min(low[u], low[v]); }\n      else if (inStk[v]) low[u] = min(low[u], dfn[v]);\n    }\n    if (low[u] == dfn[u]) {\n      int x;\n      do {\n        x = stk.back(); stk.pop_back();\n        inStk[x] = 0; belong[x] = cnt;\n      } while (x != u);\n      cnt++;\n    }\n  }\n  void run() { for (int i = 0; i < n; i++) if (!dfn[i]) dfs(i); }\n};',
    },
    {
        'category': '图论',
        'sub': '拓扑序',
        'name': '拓扑排序 (Kahn)',
            'quality': 'complete',
        'aliases': ['topo', '拓扑'],
        'intro': '入度为零的结点入队，删除其出边；返回序长 < n 说明有环。',
        'complexity': 'O(V+E)',
        'cpp': 'vector<int> topoSort(int n, const vector<vector<int>>& g) {\n  vector<int> indeg(n);\n  for (int u = 0; u < n; u++)\n    for (int v : g[u]) indeg[v]++;\n  queue<int> q;\n  for (int i = 0; i < n; i++) if (indeg[i] == 0) q.push(i);\n  vector<int> order;\n  while (!q.empty()) {\n    int u = q.front(); q.pop();\n    order.push_back(u);\n    for (int v : g[u]) if (--indeg[v] == 0) q.push(v);\n  }\n  return order;  // size < n 说明有环\n}',
    },
    {
        'category': '图论',
        'sub': 'DFS / BFS',
        'name': '连通块染色',
            'quality': 'complete',
        'aliases': ['连通块', 'flood fill', 'dfs and similar'],
        'intro': 'DFS/BFS 遍历相邻同色/可达点，给每个连通块编号。',
        'complexity': 'O(nm)',
        'cpp': 'int dx[4]={1,-1,0,0}, dy[4]={0,0,1,-1};\nvoid dfs(int x,int y,int id){\n  color[x][y]=id;\n  for(int k=0;k<4;k++){\n    int nx=x+dx[k], ny=y+dy[k];\n    if(valid(nx,ny) && color[nx][ny]==0) dfs(nx,ny,id);\n  }\n}',
    },
    {
        'category': '图论',
        'sub': 'DFS / BFS',
        'name': '二分图染色判定',
            'quality': 'complete',
        'aliases': ['二分图', 'bipartite', '染色'],
        'intro': '黑白染色，若相邻点同色则不是二分图。',
        'complexity': 'O(n+m)',
        'cpp': 'bool dfs(int u,int c){\n  color[u]=c;\n  for(int v:g[u]){\n    if(color[v]==c) return false;\n    if(!color[v] && !dfs(v,3-c)) return false;\n  }\n  return true;\n}',
    },
    {
        'category': '图论',
        'sub': 'DFS / BFS',
        'name': '简单回溯',
            'quality': 'complete',
        'aliases': ['回溯', 'backtracking', '排列'],
        'intro': '递归枚举所有排列/选择，通过剪枝减少无用分支。',
        'complexity': 'O(排列数 × 检查)',
        'cpp': 'void dfs(int dep){\n  if(dep==n){ /* 得到一个排列 */ return; }\n  for(int i=0;i<n;i++) if(!used[i]){\n    used[i]=1; path[dep]=i; dfs(dep+1); used[i]=0;\n  }\n}',
    },
    {
        'category': '图论',
        'sub': '进阶图论',
        'name': '割点 / 桥',
            'quality': 'complete',
        'aliases': ['割点', '桥', 'tarjan', 'articulation'],
        'intro': 'Tarjan 的 dfn/low 判定：low[v] >= dfn[u] 为割点，low[v] > dfn[u] 为桥。',
        'complexity': 'O(n+m)',
        'cpp': 'void tarjan(int u,int fa){\n  dfn[u]=low[u]=++timer; int child=0;\n  for(int v:g[u]){\n    if(v==fa) continue;\n    if(!dfn[v]){\n      child++;\n      tarjan(v,u);\n      low[u]=min(low[u], low[v]);\n      if(low[v]>=dfn[u] && fa!=-1) isCut[u]=1;\n      if(low[v]>dfn[u]) isBridge[make_pair(u,v)]=1;\n    } else low[u]=min(low[u], dfn[v]);\n  }\n  if(fa==-1 && child>1) isCut[u]=1;\n}',
    },
    {
        'category': '图论',
        'sub': '进阶图论',
        'name': '拓扑排序 + DAG DP',
            'quality': 'complete',
        'aliases': ['DAG 最长路', '拓扑 DP'],
        'intro': '按拓扑序转移，可求 DAG 最长路、方案数等。',
        'complexity': 'O(n+m)',
        'cpp': 'vector<int> topo = topoSort(n, g); // Kahn\nvector<long long> dp(n, -INF);\nfor (int u : topo) if (dp[u] != -INF)\n  for (int v : g[u]) dp[v] = max(dp[v], dp[u] + w[u][v]);',
    },
    {
        'category': '图论',
        'sub': '进阶图论',
        'name': '二分图最大匹配（匈牙利）',
            'quality': 'complete',
        'aliases': ['匈牙利', '二分图匹配', 'graph matchings'],
        'intro': '对每个左部点尝试增广，visited 避免重复。',
        'complexity': 'O(n·m)',
        'cpp': 'vector<int> matchR(m, -1);\nbool dfs(int u){\n  for(int v:g[u]){\n    if(vis[v]) continue; vis[v]=1;\n    if(matchR[v]==-1 || dfs(matchR[v])) { matchR[v]=u; return true; }\n  }\n  return false;\n}\nint hungarian(){ int cnt=0; for(int u=0;u<n;u++){ fill(vis.begin(),vis.end(),0); if(dfs(u)) cnt++; } return cnt; }',
    },
    {
        'category': '图论',
        'sub': '进阶图论',
        'name': 'KM 算法',
            'quality': 'complete',
        'aliases': ['KM', '最大权匹配'],
        'intro': '带权二分图完美匹配 O(n³)，维护可行顶标与相等子图。',
        'complexity': 'O(n³)',
        'cpp': '// 标准 O(n^3) KM 板子：w[i][j] 为边权，求最大权完美匹配\nvector<long long> lx(n), ly(m), slack(m);\nvector<int> match(m), pre(m);\nvector<char> visL(n), visR(m);\n// 对每个左部点 BFS 增广，维护 slack 与 pre；找不到相等边时降顶标\n// 只背板子，不在此展开全部实现',
    },
    {
        'category': '图论',
        'sub': '进阶图论',
        'name': '2-SAT',
            'quality': 'complete',
        'aliases': ['2-sat', '2-SAT'],
        'intro': '每个变量拆成真/假两点，按蕴含式建边，Tarjan 缩点后判 x 与 ¬x 是否同环。',
        'complexity': 'O(n+m)',
        'cpp': 'vector<vector<int>> g;\nvoid addImp(int u, int v) { g[u].push_back(v); } // a -> b\n// 变量 x 拆成 2x 和 2x^1，按蕴含式建边后跑 Tarjan SCC\n// 若 belong[2x] == belong[2x^1] 无解；否则取 belong 较小者为真\n// SCC 板子见「Tarjan 求 SCC」',
    },
    {
        'category': '树',
        'sub': '树上基础',
        'name': 'LCA（倍增）',
            'quality': 'complete',
        'aliases': ['lca', '最近公共祖先', '倍增'],
        'intro': '预处理 up[k][u] 倍增祖先，O(log n) 求 LCA。',
        'complexity': 'O(n log n) 预处理 / O(log n) 查询',
        'cpp': 'int lca(int u,int v){\n  if(dep[u]<dep[v]) swap(u,v);\n  for(int k=LOG-1;k>=0;k--) if(dep[up[k][u]]>=dep[v]) u=up[k][u];\n  if(u==v) return u;\n  for(int k=LOG-1;k>=0;k--) if(up[k][u]!=up[k][v]) { u=up[k][u]; v=up[k][v]; }\n  return up[0][u];\n}',
    },
    {
        'category': '树',
        'sub': '树上基础',
        'name': '树上差分',
            'quality': 'complete',
        'aliases': ['树上差分', '点差分', '边差分'],
        'intro': '路径 u-v 加 1：点差分 diff[u]++, diff[v]++, diff[lca]--, diff[fa[lca]]--；边差分类似。',
        'complexity': 'O(n log n)（需 LCA）',
        'cpp': 'vector<long long> diff(n);\nvoid dfsDiff(int u, int fa) {\n  for (int v : g[u]) if (v != fa) {\n    dfsDiff(v, u);\n    diff[u] += diff[v];\n  }\n}\n// 路径 u-v 点差分：diff[u]++, diff[v]++, diff[lca]--, diff[fa[lca]]--\n// 最后 dfsDiff(root, -1) 累加子树和还原',
    },
    {
        'category': '树',
        'sub': '树上基础',
        'name': '树的直径 / 重心',
            'quality': 'complete',
        'aliases': ['树的直径', '树的重心'],
        'intro': '直径：两次 DFS 找最远点；重心：最大子树最小的点。',
        'complexity': 'O(n)',
        'cpp': 'int dfs(int u,int fa){\n  int far=u;\n  for(int v:g[u]) if(v!=fa){ int t=dfs(v,u); if(dep[t]>dep[far]) far=t; }\n  return far;\n}\n// 直径端点 = dfs(dfs(0,-1), -1)',
    },
    {
        'category': '树',
        'sub': '进阶树论',
        'name': '基环树 DP',
            'quality': 'complete',
        'aliases': ['基环树', '环套树'],
        'intro': '先找环，断环成链后做两次树形 DP，枚举环上某点的选择状态。',
        'complexity': 'O(n)',
        'cpp': 'vector<int> deg(n), inCycle(n, 1);\nqueue<int> q;\nfor (int i = 0; i < n; i++) if (deg[i] == 1) q.push(i);\nwhile (!q.empty()) {\n  int u = q.front(); q.pop();\n  inCycle[u] = 0;\n  for (int v : g[u]) if (--deg[v] == 1) q.push(v);\n}\n// 环上点：inCycle[u] == 1\n// 断环：枚举环上一条边不选，分别以两端为根做两次树形 DP',
    },
    {
        'category': '树',
        'sub': '进阶树论',
        'name': '仙人掌 / 圆方树',
            'quality': 'complete',
        'aliases': ['仙人掌', '圆方树', 'cactus'],
        'intro': '静态建圆方树：环建方点，把仙人掌转成树后跑树形 DP。',
        'complexity': 'O(n+m)',
        'cpp': 'vector<int> dfn(n), low(n);\nvector<vector<int>> tree(n); // 圆方树，n 为原图点数\nint timer = 0;\nvoid tarjanCactus(int u, int fa) {\n  dfn[u] = low[u] = ++timer;\n  for (int v : g[u]) {\n    if (v == fa) continue;\n    if (!dfn[v]) {\n      tarjanCactus(v, u);\n      low[u] = min(low[u], low[v]);\n      if (low[v] > dfn[u]) tree[u].push_back(v), tree[v].push_back(u); // 桥\n      // low[v] == dfn[u] 时新建方点，把环上点连向方点\n    } else low[u] = min(low[u], dfn[v]);\n  }\n}\n// 之后在圆方树上做树形 DP',
    },
    {
        'category': '动态规划',
        'sub': '线性 DP',
        'name': 'LIS（最长上升子序列）',
            'quality': 'complete',
        'aliases': ['最长上升子序列', 'lis'],
        'intro': '求序列中最长的严格递增子序列长度；tail 数组维护各长度末尾最小值。',
        'complexity': 'O(n log n)',
        'cpp': 'int lis(const vector<int>& a) {\n  vector<int> tail;\n  for (int x : a) {\n    auto it = lower_bound(tail.begin(), tail.end(), x);\n    if (it == tail.end()) tail.push_back(x);\n    else *it = x;\n  }\n  return (int)tail.size();\n}',
    },
    {
        'category': '动态规划',
        'sub': '线性 DP',
        'name': 'LCS（最长公共子序列）',
            'quality': 'complete',
        'aliases': ['最长公共子序列', 'lcs'],
        'intro': '求两个序列的最长公共子序列长度，经典二维 DP。',
        'complexity': 'O(n·m)',
        'cpp': 'int lcs(const string& a, const string& b) {\n  int n = a.size(), m = b.size();\n  vector<vector<int>> dp(n + 1, vector<int>(m + 1));\n  for (int i = 1; i <= n; i++)\n    for (int j = 1; j <= m; j++)\n      dp[i][j] = a[i-1] == b[j-1]\n        ? dp[i-1][j-1] + 1\n        : max(dp[i-1][j], dp[i][j-1]);\n  return dp[n][m];\n}',
    },
    {
        'category': '动态规划',
        'sub': '线性 DP',
        'name': '0/1 背包',
            'quality': 'complete',
        'aliases': ['背包', 'knapsack'],
        'intro': '每件物品最多选一次，滚动数组倒序枚举容量实现一维空间。',
        'complexity': 'O(n·W)',
        'cpp': 'int knapsack01(int W, const vector<int>& w, const vector<int>& v) {\n  vector<int> dp(W + 1);\n  for (int i = 0; i < (int)w.size(); i++)\n    for (int j = W; j >= w[i]; j--)   // 倒序：保证每件最多一次\n      dp[j] = max(dp[j], dp[j - w[i]] + v[i]);\n  return dp[W];\n}',
    },
    {
        'category': '动态规划',
        'sub': '线性 DP',
        'name': '完全背包',
            'quality': 'complete',
        'aliases': ['完全背包', 'unbounded knapsack'],
        'intro': '物品无限，滚动数组正序枚举容量即可重复选取。',
        'complexity': 'O(n·W)',
        'cpp': 'int unboundedKnapsack(int W, vector<int>& w, vector<int>& v) {\n  vector<int> dp(W+1);\n  for(int i=0;i<(int)w.size();i++)\n    for(int j=w[i]; j<=W; j++)   // 正序\n      dp[j]=max(dp[j], dp[j-w[i]]+v[i]);\n  return dp[W];\n}',
    },
    {
        'category': '动态规划',
        'sub': '区间 DP',
        'name': '石子合并',
            'quality': 'complete',
        'aliases': ['区间 DP 模板', 'interval dp'],
        'intro': '合并相邻石子堆的最小代价；先枚举区间长度，再枚举分割点。',
        'complexity': 'O(n³)（四边形不等式可优化到 O(n²)）',
        'cpp': 'int stoneMerge(const vector<int>& a) {\n  int n = a.size();\n  vector<int> pre(n + 1);\n  for (int i = 0; i < n; i++) pre[i+1] = pre[i] + a[i];\n  vector<vector<int>> dp(n, vector<int>(n, INT_MAX));\n  for (int i = 0; i < n; i++) dp[i][i] = 0;\n  for (int len = 2; len <= n; len++)\n    for (int i = 0; i + len - 1 < n; i++) {\n      int j = i + len - 1;\n      for (int k = i; k < j; k++)\n        dp[i][j] = min(dp[i][j], dp[i][k] + dp[k+1][j] + pre[j+1] - pre[i]);\n    }\n  return dp[0][n-1];\n}',
    },
    {
        'category': '动态规划',
        'sub': '树形 DP',
        'name': '树上最大权独立集',
            'quality': 'complete',
        'aliases': ['树形 DP', 'tree dp'],
        'intro': '每个点选/不选两种状态；选了则子树根不能选。',
        'complexity': 'O(n)',
        'cpp': 'vector<vector<int>> g;\nvector<int> w;\nvector<array<long long, 2>> f; // f[u][0] 不选 u，f[u][1] 选 u\nvoid dfs(int u, int fa) {\n  f[u][1] = w[u];\n  for (int v : g[u]) if (v != fa) {\n    dfs(v, u);\n    f[u][0] += max(f[v][0], f[v][1]);\n    f[u][1] += f[v][0];\n  }\n}\n// 答案：max(f[root][0], f[root][1])，需先 f.resize(n) 并 dfs(root, -1)',
    },
    {
        'category': '动态规划',
        'sub': '状压 DP',
        'name': 'TSP（状压）',
            'quality': 'complete',
        'aliases': ['状态压缩', 'bitmask dp'],
        'intro': 'dp[s][i]：已访问集合 s、停在 i 的最短路径；从 0 出发回到 0。',
        'complexity': 'O(2ⁿ·n²)',
        'cpp': 'int tsp(int n, const vector<vector<int>>& d) {\n  int m = 1 << n;\n  vector<vector<int>> dp(m, vector<int>(n, 1e9));\n  dp[1][0] = 0;\n  for (int s = 1; s < m; s++)\n    for (int i = 0; i < n; i++)\n      if (s >> i & 1)\n        for (int j = 0; j < n; j++)\n          if (!(s >> j & 1))\n            dp[s | 1 << j][j] = min(dp[s | 1 << j][j], dp[s][i] + d[i][j]);\n  int ans = 1e9;\n  for (int i = 0; i < n; i++) ans = min(ans, dp[m - 1][i] + d[i][0]);\n  return ans;\n}',
    },
    {
        'category': '动态规划',
        'sub': '数位 DP',
        'name': '数位 DP（不含 4）',
            'quality': 'complete',
        'aliases': ['digit dp', '数位统计'],
        'intro': '从高位到低位记忆化搜索；tight 表示是否贴上界。统计 [L,R] = f(R) - f(L-1)。',
        'complexity': 'O(位数 × 状态数)',
        'cpp': "long long countNoFour(long long n) {\n  string s = to_string(n);\n  int len = s.size();\n  long long memo[20][2];\n  memset(memo, -1, sizeof(memo));\n  function<long long(int,int)> dfs = [&](int pos, int tight) -> long long {\n    if (pos == len) return 1;\n    if (!tight && memo[pos][0] != -1) return memo[pos][0];\n    int up = tight ? s[pos] - '0' : 9;\n    long long res = 0;\n    for (int d = 0; d <= up; d++) {\n      if (d == 4) continue;\n      res += dfs(pos + 1, tight && d == up);\n    }\n    if (!tight) memo[pos][0] = res;\n    return res;\n  };\n  return dfs(0, 1);\n}\n// 答案：[L,R] = countNoFour(R) - countNoFour(L-1)",
    },
    {
        'category': '动态规划',
        'sub': 'DP 优化',
        'name': '斜率优化（CHT）',
            'quality': 'complete',
        'aliases': ['斜率优化', 'CHT', 'convex hull trick'],
        'intro': '转移含 i*j 乘积项时，把候选决策看成直线，用单调队列维护凸壳。',
        'complexity': 'O(n) 或 O(n log n)',
        'cpp': '// dp[i] = min_{j<i}(dp[j] + a[i]*b[j])，b[j] 单调时可用单调队列\nlong long X(int j){ return b[j]; }\nlong long Y(int j){ return dp[j]; }\nlong long slope(int j,int k){ return (Y(j)-Y(k))/(X(j)-X(k)); }\n// 队首为最优，插入时维护斜率单调',
    },
    {
        'category': '动态规划',
        'sub': 'DP 优化',
        'name': '四边形不等式优化',
            'quality': 'complete',
        'aliases': ['四边形不等式', '决策单调'],
        'intro': '区间 DP 若满足四边形不等式，最优决策点单调，可把 O(n³) 优化到 O(n²)。',
        'complexity': 'O(n²)',
        'cpp': 'for(int len=2; len<=n; len++)\n  for(int i=1; i+len-1<=n; i++){\n    int j=i+len-1;\n    for(int k=opt[i][j-1]; k<=opt[i+1][j]; k++)\n      if(dp[i][k]+dp[k+1][j]+cost(i,j) < dp[i][j])\n        dp[i][j]=..., opt[i][j]=k;\n  }',
    },
    {
        'category': '动态规划',
        'sub': '轮廓线 DP',
        'name': '轮廓线 DP（简单棋盘状压）',
            'quality': 'complete',
        'aliases': ['轮廓线', 'plug dp', '插头 DP'],
        'intro': '逐格转移，用二进制表示当前行/列轮廓线状态，常用于棋盘覆盖计数。',
        'complexity': 'O(n·m·2^m)',
        'cpp': 'int contourDP(int n, int m) {\n  vector<int> dp(1 << m), ndp;\n  dp[0] = 1;\n  for (int i = 0; i < n; i++)\n    for (int j = 0; j < m; j++) {\n      ndp.assign(1 << m, 0);\n      for (int mask = 0; mask < (1 << m); mask++) if (dp[mask]) {\n        if (mask >> j & 1) {\n          ndp[mask & ~(1 << j)] += dp[mask];          // 当前格已被覆盖\n        } else {\n          if (j + 1 < m && !(mask >> (j + 1) & 1))\n            ndp[mask | (1 << (j + 1))] += dp[mask];    // 横放\n          ndp[mask | (1 << j)] += dp[mask];            // 竖放\n        }\n      }\n      dp.swap(ndp);\n    }\n  return dp[0];\n}',
    },
    {
        'category': '字符串',
        'sub': '模式匹配',
        'name': 'KMP',
            'quality': 'complete',
        'aliases': ['克努特-莫里斯-普拉特', 'kmp'],
        'intro': '利用失配时已匹配前缀的信息（next 数组）线性匹配，不回溯文本指针。',
        'complexity': 'O(n + m)',
        'cpp': 'vector<int> buildNext(const string& p) {\n  int m = p.size();\n  vector<int> nxt(m);\n  for (int i = 1, j = 0; i < m; i++) {\n    while (j > 0 && p[i] != p[j]) j = nxt[j-1];\n    if (p[i] == p[j]) j++;\n    nxt[i] = j;\n  }\n  return nxt;\n}\nvector<int> kmp(const string& t, const string& p) {\n  vector<int> nxt = buildNext(p), pos;\n  for (int i = 0, j = 0; i < (int)t.size(); i++) {\n    while (j > 0 && t[i] != p[j]) j = nxt[j-1];\n    if (t[i] == p[j]) j++;\n    if (j == (int)p.size()) { pos.push_back(i - j + 1); j = nxt[j-1]; }\n  }\n  return pos;\n}',
    },
    {
        'category': '字符串',
        'sub': '模式匹配',
        'name': 'Z-function',
            'quality': 'complete',
        'aliases': ['Z 算法', 'z 函数'],
        'intro': '对每个位置求与串前缀的最长公共前缀长度，可替代 KMP 做模式匹配。',
        'complexity': 'O(n)',
        'cpp': 'vector<int> zFunction(const string& s) {\n  int n = s.size();\n  vector<int> z(n);\n  for (int i = 1, l = 0, r = 0; i < n; i++) {\n    if (i <= r) z[i] = min(r - i + 1, z[i - l]);\n    while (i + z[i] < n && s[z[i]] == s[i + z[i]]) z[i]++;\n    if (i + z[i] - 1 > r) { l = i; r = i + z[i] - 1; }\n  }\n  return z;\n}',
    },
    {
        'category': '字符串',
        'sub': '多模式匹配',
        'name': 'AC 自动机',
            'quality': 'complete',
        'aliases': ['ac automaton', '多模式匹配'],
        'intro': 'Trie + fail 指针：把多个模式串建成自动机，一次扫描统计全部出现。',
        'complexity': 'O(总长度 × 字符集 + 文本长度)',
        'cpp': "struct Aho {\n  struct Node { int ch[26]; int fail = 0, cnt = 0;\n    Node() { memset(ch, 0, sizeof(ch)); } };\n  vector<Node> t{1};\n  void insert(const string& s) {\n    int u = 0;\n    for (char c : s) {\n      int k = c - 'a';\n      if (!t[u].ch[k]) { t[u].ch[k] = (int)t.size(); t.emplace_back(); }\n      u = t[u].ch[k];\n    }\n    t[u].cnt++;\n  }\n  void build() {\n    queue<int> q;\n    for (int k = 0; k < 26; k++) if (t[0].ch[k]) q.push(t[0].ch[k]);\n    while (!q.empty()) {\n      int u = q.front(); q.pop();\n      for (int k = 0; k < 26; k++) {\n        int v = t[u].ch[k];\n        if (v) { t[v].fail = t[t[u].fail].ch[k]; q.push(v); }\n        else t[u].ch[k] = t[t[u].fail].ch[k];\n      }\n    }\n  }\n  int query(const string& s) { // 统计模式串出现次数（每个串最多计一次）\n    int u = 0, res = 0;\n    for (char c : s) {\n      u = t[u].ch[c - 'a'];\n      for (int v = u; v && t[v].cnt != -1; v = t[v].fail) {\n        res += t[v].cnt; t[v].cnt = -1;\n      }\n    }\n    return res;\n  }\n};",
    },
    {
        'category': '字符串',
        'sub': '多模式匹配',
        'name': 'AC 自动机 + 矩阵快速幂',
            'quality': 'complete',
        'aliases': ['AC 自动机 + 矩阵快速幂', 'ac automaton matrix'],
        'intro': '把 AC 自动机状态建成转移矩阵，用矩阵快速幂统计长度为 L 且不含模式串的方案数。',
        'complexity': 'O(S³ log L)（S 为状态数）',
        'cpp': 'struct Mat { long long a[K][K]; };\nMat buildACMatrix(Aho& aho, long long mod) {\n  Mat M{};\n  for (int u = 0; u < (int)aho.t.size(); u++)\n    for (int c = 0; c < 26; c++) {\n      int v = aho.t[u].ch[c];\n      if (!aho.danger[v]) M.a[u][v] = (M.a[u][v] + 1) % mod;\n    }\n  return M;\n}\n// 方案数 = (初始向量 * Mat^L) 的所有合法状态之和',
    },
    {
        'category': '字符串',
        'sub': '后缀结构',
        'name': '后缀数组 (SA)',
            'quality': 'complete',
        'aliases': ['suffix array', 'sa'],
        'intro': '倍增法对后缀排序；配合 height 数组可做 LCP、子串统计等问题。',
        'complexity': 'O(n log n)',
        'cpp': 'vector<int> buildSA(const string& s) {\n  int n = (int)s.size();\n  vector<int> sa(n), rk(n), tmp(n);\n  iota(sa.begin(), sa.end(), 0);\n  for (int i = 0; i < n; i++) rk[i] = s[i];\n  for (int k = 1; k < n; k <<= 1) {\n    auto cmp = [&](int i, int j) {\n      if (rk[i] != rk[j]) return rk[i] < rk[j];\n      int ri = i + k < n ? rk[i + k] : -1;\n      int rj = j + k < n ? rk[j + k] : -1;\n      return ri < rj;\n    };\n    sort(sa.begin(), sa.end(), cmp);\n    tmp[sa[0]] = 0;\n    for (int i = 1; i < n; i++)\n      tmp[sa[i]] = tmp[sa[i-1]] + (cmp(sa[i-1], sa[i]) ? 1 : 0);\n    rk = tmp;\n  }\n  return sa; // sa[i]：排名第 i 的后缀起点\n}',
    },
    {
        'category': '字符串',
        'sub': '后缀结构',
        'name': 'Manacher',
            'quality': 'complete',
        'aliases': ['马拉车', '最长回文'],
        'intro': '线性求每个位置的最长回文半径（# 填充统一奇偶长度）。',
        'complexity': 'O(n)',
        'cpp': 'vector<int> manacher(const string& s) {\n  string t = "#";\n  for (char c : s) { t += c; t += \'#\'; }\n  int n = t.size();\n  vector<int> r(n);\n  for (int i = 0, c = 0, R = 0; i < n; i++) {\n    r[i] = i < R ? min(R - i, r[2 * c - i]) : 1;\n    while (i - r[i] >= 0 && i + r[i] < n && t[i - r[i]] == t[i + r[i]]) r[i]++;\n    if (i + r[i] > R) { c = i; R = i + r[i]; }\n  }\n  return r;  // 原串以 i/2 为中心的回文半径 = r[i]/2（下取整）\n}',
    },
    {
        'category': '字符串',
        'sub': '后缀结构',
        'name': 'SAM（后缀自动机）',
            'quality': 'complete',
        'aliases': ['SAM', '后缀自动机', 'suffix automaton'],
        'intro': '线性建图；本质不同子串数 = Σ(len[link[i]] - len[i])，两个串 LCS 可在 SAM 上跑匹配。',
        'complexity': 'O(n) 建图 / O(n) 统计',
        'cpp': 'struct SAM {\n  struct Node { int len=0, link=-1, next[26]; Node(){ memset(next,0,sizeof(next)); } };\n  vector<Node> st{1}; int last=0;\n  void extend(int c){\n    int cur=st.size(); st.push_back(Node()); st[cur].len=st[last].len+1;\n    int p=last;\n    while(p!=-1 && !st[p].next[c]) { st[p].next[c]=cur; p=st[p].link; }\n    if(p==-1) st[cur].link=0;\n    else {\n      int q=st[p].next[c];\n      if(st[p].len+1==st[q].len) st[cur].link=q;\n      else {\n        int clone=st.size(); st.push_back(st[q]); st[clone].len=st[p].len+1;\n        while(p!=-1 && st[p].next[c]==q) { st[p].next[c]=clone; p=st[p].link; }\n        st[q].link=st[cur].link=clone;\n      }\n    }\n    last=cur;\n  }\n};',
    },
    {
        'category': '字符串',
        'sub': '哈希与字典树',
        'name': 'Trie（字典树）',
            'quality': 'complete',
        'aliases': ['前缀树', 'trie'],
        'intro': '用共享前缀的树存储字符串集合，支持插入与查询 O(长度)。',
        'complexity': 'O(|S|) 每次操作',
        'cpp': "struct Trie {\n  struct Node { int ch[26]{}; int cnt = 0; };\n  vector<Node> t{1};\n  void insert(const string& s) {\n    int u = 0;\n    for (char c : s) {\n      int k = c - 'a';\n      if (!t[u].ch[k]) { t[u].ch[k] = (int)t.size(); t.emplace_back(); }\n      u = t[u].ch[k];\n    }\n    t[u].cnt++;\n  }\n  int count(const string& s) const {\n    int u = 0;\n    for (char c : s) {\n      int k = c - 'a';\n      if (!t[u].ch[k]) return 0;\n      u = t[u].ch[k];\n    }\n    return t[u].cnt;\n  }\n};",
    },
    {
        'category': '字符串',
        'sub': '哈希与字典树',
        'name': '字符串哈希（Rolling Hash）',
            'quality': 'complete',
        'aliases': ['哈希', '双哈希'],
        'intro': '把字符串映射为多项式哈希，O(1) 比较任意子串（配合前缀哈希）。',
        'complexity': 'O(n) 预处理 / O(1) 子串比较',
        'cpp': 'struct StrHash {\n  static constexpr long long MOD = 1e9 + 7, BASE = 911382323;\n  vector<long long> h, pw;\n  StrHash(const string& s) : h(s.size()+1), pw(s.size()+1) {\n    pw[0] = 1;\n    for (int i = 0; i < (int)s.size(); i++) {\n      h[i+1] = (h[i] * BASE + s[i]) % MOD;\n      pw[i+1] = pw[i] * BASE % MOD;\n    }\n  }\n  long long get(int l, int r) {  // [l, r)\n    return (h[r] - h[l] * pw[r - l] % MOD + MOD) % MOD;\n  }\n};',
    },
    {
        'category': '数论',
        'sub': '素数筛',
        'name': '线性筛（欧拉筛）',
            'quality': 'complete',
        'aliases': ['素数筛', '线性筛', 'euler sieve'],
        'intro': '每个合数只被最小质因子筛掉一次，同时可求最小质因子与欧拉函数。',
        'complexity': 'O(n)',
        'cpp': 'vector<int> linearSieve(int n) {\n  vector<int> primes, minp(n + 1);\n  for (int i = 2; i <= n; i++) {\n    if (!minp[i]) { minp[i] = i; primes.push_back(i); }\n    for (int p : primes) {\n      if (p > minp[i] || 1LL * i * p > n) break;\n      minp[i * p] = p;\n    }\n  }\n  return primes;\n}',
    },
    {
        'category': '数论',
        'sub': '素数筛',
        'name': '埃氏筛',
            'quality': 'complete',
        'aliases': ['埃氏筛', '埃拉托斯特尼', 'sieve'],
        'intro': '从小到大标记倍数；常数小，适合 1e7 内。',
        'complexity': 'O(n log log n)',
        'cpp': 'vector<bool> isPrime(n+1, true); isPrime[0]=isPrime[1]=false;\nfor(int i=2;i*i<=n;i++) if(isPrime[i])\n  for(int j=i*i;j<=n;j+=i) isPrime[j]=false;',
    },
    {
        'category': '数论',
        'sub': '素数筛',
        'name': '素数判定（试除法）',
            'quality': 'complete',
        'aliases': ['素数判定', 'isPrime'],
        'intro': '试除到 √n；小数据够用。',
        'complexity': 'O(√n)',
        'cpp': 'bool isPrime(long long n){\n  if(n<2) return false;\n  for(long long i=2;i*i<=n;i++) if(n%i==0) return false;\n  return true;\n}',
    },
    {
        'category': '数论',
        'sub': '欧拉函数',
        'name': '欧拉函数',
            'quality': 'complete',
        'aliases': ['phi', '欧拉'],
        'intro': 'φ(n) = n × ∏(1 - 1/p)；分解质因数 O(√n) 单点求，线性筛可批量求。',
        'complexity': 'O(√n) 单点 / O(n) 批量',
        'cpp': 'long long phi(long long n) {\n  long long res = n;\n  for (long long p = 2; p * p <= n; p++) {\n    if (n % p == 0) {\n      res = res / p * (p - 1);\n      while (n % p == 0) n /= p;\n    }\n  }\n  if (n > 1) res = res / n * (n - 1);\n  return res;\n}\nvector<int> phiAll(int N) { // 线性筛求 1..N 全部欧拉函数\n  vector<int> phi(N + 1), primes;\n  vector<bool> is(N + 1, false);\n  phi[1] = 1;\n  for (int i = 2; i <= N; i++) {\n    if (!is[i]) { is[i] = true; primes.push_back(i); phi[i] = i - 1; }\n    for (int p : primes) {\n      if (1LL * i * p > N) break;\n      is[i * p] = true;\n      if (i % p == 0) { phi[i * p] = phi[i] * p; break; }\n      phi[i * p] = phi[i] * (p - 1);\n    }\n  }\n  return phi;\n}',
    },
    {
        'category': '数论',
        'sub': '快速幂与逆元',
        'name': '快速幂',
            'quality': 'complete',
        'aliases': ['modpow', '幂'],
        'intro': '二进制拆分指数，O(log n) 求 a^b mod m；m 为素数时 a^(m-2) 即逆元。',
        'complexity': 'O(log b)',
        'cpp': 'long long modpow(long long a, long long b, long long m) {\n  long long r = 1;\n  while (b > 0) {\n    if (b & 1) r = r * a % m;\n    a = a * a % m;\n    b >>= 1;\n  }\n  return r;\n}',
    },
    {
        'category': '数论',
        'sub': '快速幂与逆元',
        'name': '扩展欧几里得 (exgcd)',
            'quality': 'complete',
        'aliases': ['exgcd', '逆元'],
        'intro': '求解 ax + by = gcd(a,b) 的一组整数解；x 即 a 模 b 的逆元（互素时）。',
        'complexity': 'O(log min(a,b))',
        'cpp': 'long long exgcd(long long a, long long b, long long& x, long long& y) {\n  if (b == 0) { x = 1; y = 0; return a; }\n  long long g = exgcd(b, a % b, y, x);\n  y -= a / b * x;\n  return g;\n}\n// 逆元：exgcd(a, m, x, y) 后 x 为 a 模 m 的逆（需 gcd(a,m)==1）',
    },
    {
        'category': '数论',
        'sub': '快速幂与逆元',
        'name': '费马小定理求逆元',
            'quality': 'complete',
        'aliases': ['逆元', '费马小定理', 'modular inverse'],
        'intro': '模数为素数 p 时，a 的逆元为 a^(p-2) mod p。',
        'complexity': 'O(log p)',
        'cpp': 'long long inv(long long a, long long mod){ return modpow(a, mod-2, mod); }',
    },
    {
        'category': '数论',
        'sub': '组合数学',
        'name': '组合数（预处理阶乘）',
            'quality': 'complete',
        'aliases': ['组合数学', 'comb', 'C(n,k)'],
        'intro': '预处理阶乘与逆元阶乘，O(1) 回答组合数；p 为大素数。',
        'complexity': 'O(n) 预处理 / O(1) 查询',
        'cpp': 'struct Comb {\n  vector<long long> fac, ifac; long long mod;\n  Comb(int n, long long m) : fac(n+1), ifac(n+1), mod(m) {\n    fac[0] = 1;\n    for (int i = 1; i <= n; i++) fac[i] = fac[i-1] * i % mod;\n    ifac[n] = modpow(fac[n], mod - 2, mod);\n    for (int i = n; i > 0; i--) ifac[i-1] = ifac[i] * i % mod;\n  }\n  long long C(int a, int b) {\n    if (a < 0 || b < 0 || b > a) return 0;\n    return fac[a] * ifac[b] % mod * ifac[a - b] % mod;\n  }\n};',
    },
    {
        'category': '数论',
        'sub': '组合数学',
        'name': '中国剩余定理 (CRT)',
            'quality': 'complete',
        'aliases': ['crt', '同余方程组'],
        'intro': '求解同余方程组 x ≡ a_i (mod m_i)，模数两两互素；答案对 M=∏m_i 唯一。',
        'complexity': 'O(k log m)（k 为方程个数）',
        'cpp': 'long long crt(const vector<long long>& a, const vector<long long>& m) {\n  long long M = 1, x = 0;\n  for (long long v : m) M *= v;\n  for (size_t i = 0; i < a.size(); i++) {\n    long long Mi = M / m[i], t, y;\n    exgcd(Mi % m[i], m[i], t, y);\n    t = (t % m[i] + m[i]) % m[i];\n    x = (x + a[i] * Mi % M * t) % M;\n  }\n  return (x % M + M) % M;\n}',
    },
    {
        'category': '数论',
        'sub': '组合数学',
        'name': 'Lucas 定理',
            'quality': 'complete',
        'aliases': ['Lucas', '卢卡斯'],
        'intro': 'n,m 很大但模数 p 较小时，把 n,m 写成 p 进制逐位求组合数。',
        'complexity': 'O(p log_p n)',
        'cpp': 'long long lucas(long long n, long long m, long long p){\n  if(m==0) return 1;\n  return C(n%p, m%p, p) * lucas(n/p, m/p, p) % p;\n}',
    },
    {
        'category': '数论',
        'sub': '组合数学',
        'name': '容斥原理',
            'quality': 'complete',
        'aliases': ['容斥', 'inclusion-exclusion'],
        'intro': '多个集合并集大小 = 奇数个交集和 - 偶数个交集和；常用于计数。',
        'complexity': 'O(2^k)（k 为集合数）',
        'cpp': 'long long ans=0;\nfor(int mask=1; mask<(1<<k); mask++){\n  int bits=__builtin_popcount(mask);\n  long long cur = calc(mask);\n  ans += (bits&1) ? cur : -cur;\n}',
    },
    {
        'category': '数论',
        'sub': '组合数学',
        'name': '错排 / 卡特兰数',
            'quality': 'complete',
        'aliases': ['错排', '卡特兰', 'derangement', 'catalan'],
        'intro': '错排 D[n]=(n-1)(D[n-1]+D[n-2])；卡特兰 C[n]=C[2n][n]/(n+1)。',
        'complexity': 'O(n)',
        'cpp': 'vector<long long> der(n+1); der[0]=1; der[1]=0;\nfor(int i=2;i<=n;i++) der[i]=(i-1)*(der[i-1]+der[i-2])%MOD;\nvector<long long> cat(n+1); cat[0]=1;\nfor(int i=1;i<=n;i++) cat[i]=cat[i-1]*(4*i-2)%MOD*inv(i+1,MOD)%MOD;',
    },
    {
        'category': '数论',
        'sub': '进阶数论',
        'name': '唯一分解定理',
            'quality': 'complete',
        'aliases': ['质因数分解', '唯一分解'],
        'intro': '每个正整数可唯一写成质因数乘积；试除分解 O(√n)。',
        'complexity': 'O(√n)',
        'cpp': 'vector<pair<long long,int>> factorize(long long n){\n  vector<pair<long long,int>> res;\n  for(long long p=2;p*p<=n;p++) if(n%p==0){\n    int c=0; while(n%p==0) n/=p, c++;\n    res.push_back({p,c});\n  }\n  if(n>1) res.push_back({n,1});\n  return res;\n}',
    },
    {
        'category': '数论',
        'sub': '进阶数论',
        'name': '高斯消元（异或方程组 bitset）',
            'quality': 'complete',
        'aliases': ['高斯消元', '异或方程组'],
        'intro': '用 bitset 优化异或方程组消元，复杂度 O(n³/64)。',
        'complexity': 'O(n³ / 64)',
        'cpp': 'bitset<MAXN> a[MAXN]; // a[i][j] 系数，a[i][n] 常数\nint now=0;\nfor(int col=0; col<n && now<n; col++){\n  int row=now;\n  while(row<n && !a[row][col]) row++;\n  if(row==n) continue;\n  swap(a[row], a[now]);\n  for(int i=0;i<n;i++) if(i!=now && a[i][col]) a[i]^=a[now];\n  now++;\n}',
    },
    {
        'category': '数论',
        'sub': '进阶数论',
        'name': '扩展中国剩余定理（EXCRT）',
            'quality': 'complete',
        'aliases': ['EXCRT', '扩展中国剩余定理'],
        'intro': '模数不互素时用 exgcd 两两合并同余方程。',
        'complexity': 'O(k log m)',
        'cpp': 'bool excrt(long long& x, long long& M, long long a, long long m){\n  long long g=exgcd(M, m, x, y);\n  if((a-x)%g) return false;\n  x = (x + (a-x)/g * M) % (M/g*m);\n  M = M/g*m;\n  x = (x%M+M)%M;\n  return true;\n}',
    },
    {
        'category': '数论',
        'sub': '进阶数论',
        'name': '线性基',
            'quality': 'complete',
        'aliases': ['线性基', 'linear basis'],
        'intro': '维护一组异或基，可求最大异或和与第 k 小。',
        'complexity': 'O(n log V)',
        'cpp': 'struct LinearBasis {\n  long long a[64] = {};\n  void insert(long long x){\n    for(int i=62;i>=0;i--) if(x>>i&1){\n      if(!a[i]) { a[i]=x; return; }\n      x ^= a[i];\n    }\n  }\n  long long maxXor(){\n    long long res=0;\n    for(int i=62;i>=0;i--) res=max(res, res^a[i]);\n    return res;\n  }\n};',
    },
    {
        'category': '数论',
        'sub': 'GCD / LCM',
        'name': 'GCD / LCM',
            'quality': 'complete',
        'aliases': ['gcd', 'lcm', '最大公约数', '最小公倍数'],
        'intro': '辗转相除法求 gcd，lcm = a / gcd(a,b) * b 防止溢出。',
        'complexity': 'O(log min(a,b))',
        'cpp': 'long long gcd(long long a, long long b) {\n  return b == 0 ? a : gcd(b, a % b);\n}\nlong long lcm(long long a, long long b) {\n  return a / gcd(a, b) * b;\n}',
    },
    {
        'category': '矩阵',
        'sub': '矩阵快速幂',
        'name': '矩阵快速幂优化递推',
            'quality': 'complete',
        'aliases': ['矩阵快速幂', '矩阵', 'matrices', '矩阵乘法'],
        'intro': '把线性递推写成矩阵乘法，用快速幂 O(k³ log n) 求第 n 项。',
        'complexity': 'O(k³ log n)',
        'cpp': 'struct Mat { long long a[K][K]; };\nMat mul(Mat A, Mat B){\n  Mat C{};\n  for(int i=0;i<K;i++) for(int k=0;k<K;k++) if(A.a[i][k])\n    for(int j=0;j<K;j++) C.a[i][j]=(C.a[i][j]+A.a[i][k]*B.a[k][j])%MOD;\n  return C;\n}\nMat mpow(Mat A, long long n){\n  Mat R{}; for(int i=0;i<K;i++) R.a[i][i]=1;\n  while(n){ if(n&1) R=mul(R,A); A=mul(A,A); n>>=1; }\n  return R;\n}',
    },
    {
        'category': '计算几何',
        'sub': '凸包',
        'name': 'Andrew 单调链凸包',
            'quality': 'complete',
        'aliases': ['安德鲁凸包', '凸包', 'convex hull'],
        'intro': '按 x 排序后分别构造上下链；叉积判断转向，O(n log n) 求凸包。',
        'complexity': 'O(n log n)',
        'cpp': 'struct P { long long x, y; };\nlong long cross(const P& a, const P& b, const P& c) {\n  return (b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x);\n}\nvector<P> convexHull(vector<P> p) {\n  sort(p.begin(), p.end(), [](auto& a, auto& b){ return a.x != b.x ? a.x < b.x : a.y < b.y; });\n  vector<P> h;\n  for (int pass = 0; pass < 2; pass++) {\n    int start = (int)h.size();\n    for (auto& q : p) {\n      while (h.size() >= start + 2 &&\n             cross(h[h.size()-2], h.back(), q) <= 0) h.pop_back();\n      h.push_back(q);\n    }\n    h.pop_back();\n    reverse(p.begin(), p.end());\n  }\n  return h;\n}',
    },
    {
        'category': '计算几何',
        'sub': '凸包',
        'name': '旋转卡壳',
            'quality': 'complete',
        'aliases': ['旋转卡壳', 'rotating calipers'],
        'intro': '在凸包上双指针旋转，求直径（最远点对）或最小矩形覆盖。',
        'complexity': 'O(n)（凸包后）',
        'cpp': 'long long rotatingCalipers(vector<P>& h){\n  int n=h.size(); if(n<=1) return 0;\n  int j=1; long long ans=0;\n  for(int i=0;i<n;i++){\n    while(cross(h[i], h[(i+1)%n], h[j]) < cross(h[i], h[(i+1)%n], h[(j+1)%n])) j=(j+1)%n;\n    ans=max(ans, dist2(h[i],h[j]));\n    ans=max(ans, dist2(h[(i+1)%n],h[j]));\n  }\n  return ans;\n}',
    },
    {
        'category': '计算几何',
        'sub': '最近点对',
        'name': '最近点对（分治）',
            'quality': 'complete',
        'aliases': ['closest pair'],
        'intro': '按 x 分治，跨中线候选点按 y 排序后只检查邻近点，O(n log n)。',
        'complexity': 'O(n log n)',
        'cpp': 'struct Pt { double x, y; };\ndouble dist(const Pt& a, const Pt& b) {\n  return hypot(a.x - b.x, a.y - b.y);\n}\ndouble closestPair(vector<Pt> p) {\n  sort(p.begin(), p.end(), [](auto& a, auto& b){ return a.x < b.x; });\n  function<double(int,int)> solve = [&](int l, int r) -> double {\n    if (r - l <= 1) return 1e18;\n    int m = (l + r) / 2;\n    double d = min(solve(l, m), solve(m, r));\n    double midx = p[m].x;\n    vector<Pt> strip;\n    for (int i = l; i < r; i++)\n      if (fabs(p[i].x - midx) < d) strip.push_back(p[i]);\n    sort(strip.begin(), strip.end(), [](auto& a, auto& b){ return a.y < b.y; });\n    for (int i = 0; i < (int)strip.size(); i++)\n      for (int j = i + 1; j < (int)strip.size() && strip[j].y - strip[i].y < d; j++)\n        d = min(d, dist(strip[i], strip[j]));\n    return d;\n  };\n  return solve(0, (int)p.size());\n}',
    },
    {
        'category': '计算几何',
        'sub': '线段相交',
        'name': '线段相交判定',
            'quality': 'complete',
        'aliases': ['segment intersection', '叉积'],
        'intro': '跨立实验：两端点分居对方线段两侧；再补共线端点情况。',
        'complexity': 'O(1)',
        'cpp': 'struct Pt { long long x, y; };\nlong long cross(const Pt& a, const Pt& b, const Pt& c) {\n  return (b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x);\n}\nbool onSeg(const Pt& p, const Pt& a, const Pt& b) {\n  return cross(a, b, p) == 0\n    && min(a.x, b.x) <= p.x && p.x <= max(a.x, b.x)\n    && min(a.y, b.y) <= p.y && p.y <= max(a.y, b.y);\n}\nbool segInter(const Pt& a, const Pt& b, const Pt& c, const Pt& d) {\n  long long d1 = cross(c, d, a), d2 = cross(c, d, b);\n  long long d3 = cross(a, b, c), d4 = cross(a, b, d);\n  if (((d1 > 0) != (d2 > 0)) && ((d3 > 0) != (d4 > 0))) return true;\n  return onSeg(a, c, d) || onSeg(b, c, d) || onSeg(c, a, b) || onSeg(d, a, b);\n}',
    },
    {
        'category': '计算几何',
        'sub': '向量基础',
        'name': '叉积 / 点积判断方位',
            'quality': 'complete',
        'aliases': ['叉积', '点积', '向量'],
        'intro': '叉积判断三点转向/面积，点积判断角度与投影。',
        'complexity': 'O(1)',
        'cpp': 'struct P { long long x,y; };\nlong long cross(P a,P b,P c){ return (b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x); }\nlong long dot(P a,P b,P c){ return (b.x-a.x)*(c.x-a.x)+(b.y-a.y)*(c.y-a.y); }\n// cross>0 左转，<0 右转，==0 共线；dot>0 锐角，<0 钝角',
    },
    {
        'category': '其他',
        'sub': '博弈论',
        'name': 'Nim 游戏与 SG 函数',
            'quality': 'complete',
        'aliases': ['博弈', 'nim', 'sg'],
        'intro': 'Nim：异或和为零先手必败。一般公平游戏用 SG 函数记忆化求解。',
        'complexity': 'O(n)（Nim）/ O(状态×转移)（SG）',
        'cpp': '// Nim 游戏：所有堆异或和为零 → 先手必败\nbool nimWins(const vector<long long>& piles) {\n  long long x = 0;\n  for (long long v : piles) x ^= v;\n  return x != 0;\n}\n// SG 函数（moves(x) 返回可达状态，sgMemo 初始 -1）\nint sgMemo[100005];\nint sg(int x) {\n  if (sgMemo[x] != -1) return sgMemo[x];\n  set<int> s;\n  for (int y : moves(x)) s.insert(sg(y));\n  int g = 0;\n  while (s.count(g)) g++;\n  return sgMemo[x] = g;\n}',
    },
    {
        'category': '其他',
        'sub': '概率期望',
        'name': '期望 DP（掷骰子）',
            'quality': 'complete',
        'aliases': ['概率', '期望', 'expected'],
        'intro': '从终点逆推：f[i] 表示从 i 到终点还需的期望步数，f[i] = Σ f[下一步]/6 + 1。',
        'complexity': 'O(n)',
        'cpp': 'double expectedSteps(int n) {\n  vector<double> f(n + 7);\n  for (int i = n - 1; i >= 0; i--) {\n    double s = 0;\n    for (int k = 1; k <= 6; k++) s += f[min(n, i + k)];\n    f[i] = s / 6 + 1;\n  }\n  return f[0];\n}',
    },
    {
        'category': '其他',
        'sub': '莫队',
        'name': '莫队（区间不同数）',
            'quality': 'complete',
        'aliases': ['mo algorithm', '离线区间'],
        'intro': '分块排序询问，指针左右移动维护答案；修改代价必须 O(1)。',
        'complexity': 'O((n+q)√n)',
        'cpp': 'struct Query { int l, r, id; };\nvector<int> mo(const vector<int>& a, vector<Query>& qs) {\n  int n = (int)a.size(), B = max(1, (int)sqrt(n));\n  sort(qs.begin(), qs.end(), [&](auto& x, auto& y) {\n    if (x.l / B != y.l / B) return x.l < y.l;\n    return ((x.l / B) & 1) ? x.r > y.r : x.r < y.r;\n  });\n  vector<int> cnt(1000005), ans(qs.size());\n  int cur = 0, L = 1, R = 0;\n  auto add = [&](int p) { if (cnt[a[p]]++ == 0) cur++; };\n  auto del = [&](int p) { if (--cnt[a[p]] == 0) cur--; };\n  for (auto& q : qs) {\n    while (L > q.l) add(--L);\n    while (R < q.r) add(++R);\n    while (L < q.l) del(L++);\n    while (R > q.r) del(R--);\n    ans[q.id] = cur;\n  }\n  return ans;\n}',
    },
    {
        'category': '其他',
        'sub': '主席树',
        'name': '主席树（区间第 k 小）',
            'quality': 'complete',
        'aliases': ['可持久化线段树', 'pst', '第k小'],
        'intro': '每个前缀一棵权值线段树，差分求区间内第 k 小；值域离散化。',
        'complexity': 'O((n+q) log n)',
        'cpp': 'struct PST {\n  struct Node { int l = 0, r = 0, sum = 0; };\n  vector<Node> t{{0, 0, 0}};\n  int update(int pre, int l, int r, int pos) {\n    int cur = (int)t.size();\n    t.push_back(t[pre]);\n    t[cur].sum++;\n    if (l != r) {\n      int m = (l + r) / 2;\n      if (pos <= m) t[cur].l = update(t[pre].l, l, m, pos);\n      else t[cur].r = update(t[pre].r, m + 1, r, pos);\n    }\n    return cur;\n  }\n  int query(int u, int v, int l, int r, int k) { // 返回第 k 小（离散化下标）\n    if (l == r) return l;\n    int m = (l + r) / 2;\n    int leftSum = t[t[v].l].sum - t[t[u].l].sum;\n    if (k <= leftSum) return query(t[u].l, t[v].l, l, m, k);\n    return query(t[u].r, t[v].r, m + 1, r, k - leftSum);\n  }\n};',
    },
    {'category': '数据结构', 'sub': '动态树', 'name': 'Link-Cut Tree (LCT)', 'quality': 'complete', 'aliases': ['LCT', '动态树', 'link cut tree'], 'intro': '动态树：支持 link/cut/换根/链上信息维护，核心是 Splay 维护的虚实链剖分。', 'complexity': 'O(log n) 摊还', 'cpp': 'struct LCT {\n  int ch[N][2], fa[N], rev[N], val[N], sum[N];\n  bool isroot(int x){ return ch[fa[x]][0]!=x && ch[fa[x]][1]!=x; }\n  void pushup(int x){ sum[x]=sum[ch[x][0]]^sum[ch[x][1]]^val[x]; }\n  void pushrev(int x){ swap(ch[x][0],ch[x][1]); rev[x]^=1; }\n  void pushdown(int x){ if(rev[x]){ pushrev(ch[x][0]); pushrev(ch[x][1]); rev[x]=0; } }\n  void rotate(int x){\n    int y=fa[x], z=fa[y], k=(ch[y][1]==x);\n    if(!isroot(y)) ch[z][ch[z][1]==y]=x;\n    fa[x]=z; ch[y][k]=ch[x][k^1]; if(ch[x][k^1]) fa[ch[x][k^1]]=y;\n    ch[x][k^1]=y; fa[y]=x; pushup(y); pushup(x);\n  }\n  void splay(int x){\n    static int st[N]; int y=x, top=0; st[++top]=y;\n    while(!isroot(y)) st[++top]=y=fa[y];\n    while(top) pushdown(st[top--]);\n    while(!isroot(x)){\n      int y=fa[x], z=fa[y];\n      if(!isroot(y)) rotate((ch[y][0]==x)^(ch[z][0]==y)?x:y);\n      rotate(x);\n    }\n  }\n  void access(int x){ for(int y=0; x; y=x, x=fa[x]) splay(x), ch[x][1]=y, pushup(x); }\n  void makeroot(int x){ access(x); splay(x); pushrev(x); }\n  int findroot(int x){ access(x); splay(x); while(ch[x][0]) pushdown(x), x=ch[x][0]; splay(x); return x; }\n  void link(int x,int y){ makeroot(x); if(findroot(y)!=x) fa[x]=y; }\n  void cut(int x,int y){ makeroot(x); access(y); splay(y); if(ch[y][0]==x && !ch[x][1]) ch[y][0]=fa[x]=0; }\n};'},
    {'category': '数据结构', 'sub': '树链剖分', 'name': '树链剖分 (HLD)', 'quality': 'complete', 'aliases': ['HLD', '重链剖分', '树剖'], 'intro': '重链剖分把树上路径/子树映射成 DFS 序区间，配合线段树维护路径信息。', 'complexity': 'O(log^2 n) 每次路径操作', 'cpp': 'int fa[N], dep[N], sz[N], son[N], top[N], dfn[N], rk[N], tim;\nvoid dfs1(int u,int f){\n  fa[u]=f; dep[u]=dep[f]+1; sz[u]=1; son[u]=0;\n  for(int v:g[u]) if(v!=f){\n    dfs1(v,u); sz[u]+=sz[v];\n    if(sz[v]>sz[son[u]]) son[u]=v;\n  }\n}\nvoid dfs2(int u,int t){\n  top[u]=t; dfn[u]=++tim; rk[tim]=u;\n  if(son[u]) dfs2(son[u],t);\n  for(int v:g[u]) if(v!=fa[u] && v!=son[u]) dfs2(v,v);\n}\nvoid pathUpdate(int u,int v,int val){\n  while(top[u]!=top[v]){\n    if(dep[top[u]]<dep[top[v]]) swap(u,v);\n    seg.update(dfn[top[u]],dfn[u],val);\n    u=fa[top[u]];\n  }\n  if(dep[u]>dep[v]) swap(u,v);\n  seg.update(dfn[u],dfn[v],val);\n}'},
    {'category': '数据结构', 'sub': '可持久化', 'name': '可持久化数据结构（主席树进阶）', 'quality': 'complete', 'aliases': ['可持久化线段树', 'persistent', '历史版本'], 'intro': '在更新时新建节点保留历史版本，支持查询任意历史版本；主席树是可持久化权值线段树。', 'complexity': 'O(log n) 每次操作', 'cpp': 'struct PersistentSeg {\n  struct Node { int l=0,r=0,sum=0; };\n  vector<Node> t{{0,0,0}};\n  int update(int pre,int l,int r,int pos){\n    int cur=(int)t.size(); t.push_back(t[pre]); t[cur].sum++;\n    if(l!=r){\n      int m=(l+r)/2;\n      if(pos<=m) t[cur].l=update(t[pre].l,l,m,pos);\n      else t[cur].r=update(t[pre].r,m+1,r,pos);\n    }\n    return cur;\n  }\n  int query(int u,int v,int l,int r,int k){\n    if(l==r) return l;\n    int m=(l+r)/2, left=t[t[v].l].sum-t[t[u].l].sum;\n    if(k<=left) return query(t[u].l,t[v].l,l,m,k);\n    return query(t[u].r,t[v].r,m+1,r,k-left);\n  }\n};'},
    {'category': '字符串', 'sub': '后缀结构', 'name': '后缀自动机（SAM）进阶', 'quality': 'complete', 'aliases': ['SAM 进阶', '后缀自动机', 'suffix automaton'], 'intro': '在 SAM 上按 parent 树拓扑序累加 endpos 大小，可求每个子串出现次数、本质不同子串等。', 'complexity': 'O(n) 建图 / O(n) DP', 'cpp': 'struct SAM {\n  struct Node { int len=0, link=-1, next[26]; Node(){ memset(next,0,sizeof(next)); } };\n  vector<Node> st{1}; int last=0;\n  void extend(int c){\n    int cur=st.size(); st.push_back(Node()); st[cur].len=st[last].len+1;\n    int p=last;\n    while(p!=-1 && !st[p].next[c]) { st[p].next[c]=cur; p=st[p].link; }\n    if(p==-1) st[cur].link=0;\n    else {\n      int q=st[p].next[c];\n      if(st[p].len+1==st[q].len) st[cur].link=q;\n      else {\n        int clone=st.size(); st.push_back(st[q]); st[clone].len=st[p].len+1;\n        while(p!=-1 && st[p].next[c]==q) { st[p].next[c]=clone; p=st[p].link; }\n        st[q].link=st[cur].link=clone;\n      }\n    }\n    last=cur;\n  }\n  // 按 len 桶排后倒序累加 endpos 数量\n  vector<int> countEndpos(int n){\n    vector<int> cnt(n+1), ord(st.size());\n    for(int i=1;i<(int)st.size();i++) cnt[st[i].len]++;\n    for(int i=1;i<=n;i++) cnt[i]+=cnt[i-1];\n    for(int i=(int)st.size()-1;i>=1;i--) ord[--cnt[st[i].len]]=i;\n    vector<int> sz(st.size(),0);\n    for(int u:ord) if(st[u].link!=-1) sz[st[u].link]+=sz[u];\n    return sz;\n  }\n};'},
    {'category': '字符串', 'sub': '后缀结构', 'name': '广义 SAM', 'quality': 'complete', 'aliases': ['广义后缀自动机', 'generalized SAM', '多串 SAM'], 'intro': '对多个串建立后缀自动机：插入每个串前把 last 重置为根，或先建 Trie 再 BFS 扩展。', 'complexity': 'O(总字符数)', 'cpp': 'struct GeneralSAM {\n  struct Node { int len=0, link=-1, next[26]; Node(){ memset(next,0,sizeof(next)); } };\n  vector<Node> st{1};\n  int extend(int last,int c){\n    if(st[last].next[c]){\n      int p=last, q=st[last].next[c];\n      if(st[p].len+1==st[q].len) return q;\n      int clone=st.size(); st.push_back(st[q]); st[clone].len=st[p].len+1;\n      while(p!=-1 && st[p].next[c]==q) { st[p].next[c]=clone; p=st[p].link; }\n      st[q].link=clone; return clone;\n    }\n    int cur=st.size(); st.push_back(Node()); st[cur].len=st[last].len+1;\n    int p=last;\n    while(p!=-1 && !st[p].next[c]) { st[p].next[c]=cur; p=st[p].link; }\n    if(p==-1) st[cur].link=0;\n    else {\n      int q=st[p].next[c];\n      if(st[p].len+1==st[q].len) st[cur].link=q;\n      else {\n        int clone=st.size(); st.push_back(st[q]); st[clone].len=st[p].len+1;\n        while(p!=-1 && st[p].next[c]==q) { st[p].next[c]=clone; p=st[p].link; }\n        st[q].link=st[cur].link=clone;\n      }\n    }\n    return cur;\n  }\n};'},
    {'category': '数学', 'sub': '多项式', 'name': 'FFT', 'quality': 'complete', 'aliases': ['快速傅里叶变换', 'fast fourier transform', '多项式乘法'], 'intro': '用复数单位根做 DFT/IDFT，O(n log n) 实现多项式乘法。', 'complexity': 'O(n log n)', 'cpp': 'using cd = complex<double>;\nvoid fft(vector<cd>& a, bool inv){\n  int n=a.size();\n  for(int i=1,j=0;i<n;i++){\n    int bit=n>>1;\n    for(;j&bit;bit>>=1) j^=bit;\n    j^=bit;\n    if(i<j) swap(a[i],a[j]);\n  }\n  for(int len=2;len<=n;len<<=1){\n    double ang=2*acos(-1)/len*(inv?-1:1);\n    cd wlen(cos(ang),sin(ang));\n    for(int i=0;i<n;i+=len){\n      cd w(1);\n      for(int j=0;j<len/2;j++){\n        cd u=a[i+j], v=a[i+j+len/2]*w;\n        a[i+j]=u+v; a[i+j+len/2]=u-v; w*=wlen;\n      }\n    }\n  }\n  if(inv) for(cd& x:a) x/=n;\n}\nvector<int> multiply(vector<int> A, vector<int> B){\n  int n=1; while(n<(int)(A.size()+B.size())) n<<=1;\n  vector<cd> a(n), b(n);\n  for(int i=0;i<(int)A.size();i++) a[i]=A[i];\n  for(int i=0;i<(int)B.size();i++) b[i]=B[i];\n  fft(a,false); fft(b,false);\n  for(int i=0;i<n;i++) a[i]*=b[i];\n  fft(a,true);\n  vector<int> C(A.size()+B.size()-1);\n  for(int i=0;i<(int)C.size();i++) C[i]=llround(a[i].real());\n  return C;\n}'},
    {'category': '数学', 'sub': '多项式', 'name': 'NTT', 'quality': 'complete', 'aliases': ['快速数论变换', 'number theoretic transform', '998244353'], 'intro': '在模 998244353（原根 3）下做整数多项式卷积，避免浮点误差。', 'complexity': 'O(n log n)', 'cpp': 'const int MOD=998244353, G=3;\nlong long qpow(long long a,long long b){ long long r=1; for(;b;b>>=1){ if(b&1) r=r*a%MOD; a=a*a%MOD; } return r; }\nvoid ntt(vector<int>& a,bool inv){\n  int n=a.size();\n  for(int i=1,j=0;i<n;i++){\n    int bit=n>>1;\n    for(;j&bit;bit>>=1) j^=bit;\n    j^=bit;\n    if(i<j) swap(a[i],a[j]);\n  }\n  for(int len=2;len<=n;len<<=1){\n    int wlen=qpow(G,(MOD-1)/len);\n    if(inv) wlen=qpow(wlen,MOD-2);\n    for(int i=0;i<n;i+=len){\n      long long w=1;\n      for(int j=0;j<len/2;j++){\n        int u=a[i+j], v=(int)(a[i+j+len/2]*w%MOD);\n        a[i+j]=(u+v)%MOD;\n        a[i+j+len/2]=(u-v+MOD)%MOD;\n        w=w*wlen%MOD;\n      }\n    }\n  }\n  if(inv){ long long invn=qpow(n,MOD-2); for(int& x:a) x=x*invn%MOD; }\n}'},
    {'category': '数学', 'sub': '组合计数', 'name': '生成函数', 'aliases': ['生成函数', 'generating function', '形式幂级数'], 'intro': '用形式幂级数表示数列，卷积对应组合计数；常配合 NTT 做多项式求逆/exp/ln。', 'complexity': 'O(n log n)（配合 NTT）', 'quality': 'complete', 'cpp': 'const int MOD = 998244353, G = 3;\nlong long qpow(long long a, long long b) {\n  long long r = 1;\n  for (; b; b >>= 1) { if (b & 1) r = r * a % MOD; a = a * a % MOD; }\n  return r;\n}\nvoid ntt(vector<int>& a, bool inv) {\n  int n = (int)a.size();\n  for (int i = 1, j = 0; i < n; i++) {\n    int bit = n >> 1;\n    for (; j & bit; bit >>= 1) j ^= bit;\n    j ^= bit;\n    if (i < j) swap(a[i], a[j]);\n  }\n  for (int len = 2; len <= n; len <<= 1) {\n    int wlen = qpow(G, (MOD - 1) / len);\n    if (inv) wlen = qpow(wlen, MOD - 2);\n    for (int i = 0; i < n; i += len) {\n      long long w = 1;\n      for (int j = 0; j < len / 2; j++) {\n        int u = a[i + j], v = (int)(a[i + j + len / 2] * w % MOD);\n        a[i + j] = (u + v) % MOD;\n        a[i + j + len / 2] = (u - v + MOD) % MOD;\n        w = w * wlen % MOD;\n      }\n    }\n  }\n  if (inv) { long long invn = qpow(n, MOD - 2); for (int& x : a) x = x * invn % MOD; }\n}\nvector<int> polyMul(vector<int> a, vector<int> b) {\n  int need = (int)a.size() + (int)b.size() - 1;\n  int n = 1; while (n < need) n <<= 1;\n  a.resize(n); b.resize(n);\n  ntt(a, false); ntt(b, false);\n  for (int i = 0; i < n; i++) a[i] = (long long)a[i] * b[i] % MOD;\n  ntt(a, true);\n  a.resize(need);\n  return a;\n}\n// 多项式求逆/exp/ln 可用牛顿迭代：例如求逆时维护 g，使 f*g ≡ 1 (mod x^m)。'},
    {'category': '数论', 'sub': '反演', 'name': '莫比乌斯反演', 'quality': 'complete', 'aliases': ['莫比乌斯', 'mobius', 'mu'], 'intro': '利用莫比乌斯函数和整除卷积化简 gcd/lcm 类计数问题。', 'complexity': 'O(n log log n) 筛 + O(√n) 数论分块', 'cpp': 'vector<int> mobius(int n){\n  vector<int> mu(n+1), primes; vector<bool> vis(n+1);\n  mu[1]=1;\n  for(int i=2;i<=n;i++){\n    if(!vis[i]){ primes.push_back(i); mu[i]=-1; }\n    for(int p:primes){\n      if(1LL*i*p>n) break;\n      vis[i*p]=true;\n      if(i%p==0){ mu[i*p]=0; break; }\n      mu[i*p]=-mu[i];\n    }\n  }\n  return mu;\n}\n// 例：sum_{i=1}^n sum_{j=1}^m [gcd(i,j)=1]\n// = sum_{d=1}^{min(n,m)} mu[d] * (n/d) * (m/d)，用数论分块 O(sqrt) 求。'},
    {'category': '数论', 'sub': '线性基进阶', 'name': '线性基进阶', 'quality': 'complete', 'aliases': ['线性基进阶', '区间线性基', 'linear basis'], 'intro': '线性基进阶：维护区间线性基、支持第 k 小/最大值、可离线合并。', 'complexity': 'O(n log V)', 'cpp': 'struct LinearBasis {\n  long long a[64]={}, pos[64]={};\n  void insert(long long x){\n    for(int i=62;i>=0;i--) if(x>>i&1){\n      if(!a[i]) { a[i]=x; return; }\n      x ^= a[i];\n    }\n  }\n  bool contain(long long x){\n    for(int i=62;i>=0;i--) if(x>>i&1) x ^= a[i];\n    return x==0;\n  }\n  long long maxXor(){\n    long long res=0;\n    for(int i=62;i>=0;i--) res=max(res,res^a[i]);\n    return res;\n  }\n};'},
    {'category': '计算几何', 'sub': '半平面交', 'name': '半平面交', 'aliases': ['half plane intersection', '半平面'], 'intro': '把每个半平面按极角排序，用双端队列维护交点，求交集凸多边形。', 'complexity': 'O(n log n)', 'quality': 'complete', 'cpp': 'struct Point { double x, y; };\nPoint operator+(Point a, Point b) { return {a.x + b.x, a.y + b.y}; }\nPoint operator-(Point a, Point b) { return {a.x - b.x, a.y - b.y}; }\nPoint operator*(Point a, double k) { return {a.x * k, a.y * k}; }\ndouble cross(Point a, Point b) { return a.x * b.y - a.y * b.x; }\nconst double eps = 1e-9;\nstruct Line { Point p, v; double ang; };\nbool cmp(const Line& a, const Line& b) { return a.ang < b.ang; }\nPoint inter(Line a, Line b) {\n  Point u = a.p - b.p;\n  double t = cross(b.v, u) / cross(a.v, b.v);\n  return a.p + a.v * t;\n}\nbool onLeft(Line l, Point p) { return cross(l.v, p - l.p) > eps; }\nvector<Point> halfPlane(vector<Line> lines) {\n  for (auto& l : lines) l.ang = atan2(l.v.y, l.v.x);\n  sort(lines.begin(), lines.end(), cmp);\n  deque<Line> q;\n  deque<Point> pts;\n  for (Line l : lines) {\n    while (pts.size() && !onLeft(l, pts.back())) { q.pop_back(); pts.pop_back(); }\n    while (pts.size() && !onLeft(l, pts.front())) { q.pop_front(); pts.pop_front(); }\n    if (!q.empty() && fabs(cross(q.back().v, l.v)) < eps) {\n      if (cross(q.back().v, l.p - q.back().p) < 0) return {};\n    } else {\n      q.push_back(l);\n    }\n    if (q.size() > 1) pts.push_back(inter(q[q.size() - 2], q.back()));\n  }\n  while (pts.size() && !onLeft(q.front(), pts.back())) { q.pop_back(); pts.pop_back(); }\n  if (q.size() < 3) return {};\n  return vector<Point>(pts.begin(), pts.end());\n}'},
    {'category': '计算几何', 'sub': '圆', 'name': '最小圆覆盖', 'aliases': ['最小覆盖圆', 'minimum enclosing circle'], 'intro': '随机增量法：依次加入点，若不在当前圆内则重构圆，期望 O(n)。', 'complexity': 'O(n) 期望', 'quality': 'complete', 'cpp': 'struct Point { double x, y; };\nstruct Circle { Point o; double r; };\ndouble dist(Point a, Point b) { return hypot(a.x - b.x, a.y - b.y); }\nPoint mid(Point a, Point b) { return {(a.x + b.x) / 2, (a.y + b.y) / 2}; }\nCircle circumcircle(Point a, Point b, Point c) {\n  double d = 2 * (a.x * (b.y - c.y) + b.x * (c.y - a.y) + c.x * (a.y - b.y));\n  double ux = ((a.x*a.x + a.y*a.y) * (b.y - c.y) + (b.x*b.x + b.y*b.y) * (c.y - a.y) + (c.x*c.x + c.y*c.y) * (a.y - b.y)) / d;\n  double uy = ((a.x*a.x + a.y*a.y) * (c.x - b.x) + (b.x*b.x + b.y*b.y) * (a.x - c.x) + (c.x*c.x + c.y*c.y) * (b.x - a.x)) / d;\n  Point o = {ux, uy};\n  return {o, dist(o, a)};\n}\nconst double eps = 1e-9;\nCircle minEnclosingCircle(vector<Point> p) {\n  random_shuffle(p.begin(), p.end());\n  Circle c{p[0], 0};\n  for (int i = 1; i < (int)p.size(); i++) {\n    if (dist(p[i], c.o) > c.r + eps) {\n      c = {p[i], 0};\n      for (int j = 0; j < i; j++) {\n        if (dist(p[j], c.o) > c.r + eps) {\n          c = {mid(p[i], p[j]), dist(p[i], p[j]) / 2};\n          for (int k = 0; k < j; k++) {\n            if (dist(p[k], c.o) > c.r + eps) c = circumcircle(p[i], p[j], p[k]);\n          }\n        }\n      }\n    }\n  }\n  return c;\n}'},
    {'category': '计算几何', 'sub': '三维', 'name': '三维凸包', 'aliases': ['3D convex hull', '三维凸包'], 'intro': '三维凸包常用增量法：每加入一个点，删除可见面并补上新面。', 'complexity': 'O(n^2)', 'quality': 'complete', 'cpp': 'struct Point3 { double x, y, z; };\nPoint3 operator-(Point3 a, Point3 b) { return {a.x-b.x, a.y-b.y, a.z-b.z}; }\nPoint3 cross(Point3 a, Point3 b) {\n  return {a.y*b.z - a.z*b.y, a.z*b.x - a.x*b.z, a.x*b.y - a.y*b.x};\n}\ndouble dot(Point3 a, Point3 b) { return a.x*b.x + a.y*b.y + a.z*b.z; }\ndouble volume(Point3 a, Point3 b, Point3 c, Point3 d) { return dot(cross(b-a, c-a), d-a); }\nconst double eps = 1e-9;\nstruct Face { int v[3]; };\nvector<Face> convexHull3D(vector<Point3> p) {\n  int n = (int)p.size();\n  vector<Face> faces = {{0,1,2}, {0,2,1}};\n  for (int i = 3; i < n; i++) {\n    vector<Face> nxt;\n    set<pair<int,int>> edges;\n    for (Face f : faces) {\n      if (volume(p[f.v[0]], p[f.v[1]], p[f.v[2]], p[i]) > eps) continue; // 不可见\n      nxt.push_back(f);\n      for (int j = 0; j < 3; j++) {\n        int a = f.v[j], b = f.v[(j+1)%3];\n        if (edges.count({b,a})) edges.erase({b,a});\n        else edges.insert({a,b});\n      }\n    }\n    for (auto [a,b] : edges) nxt.push_back({a,b,i});\n    faces.swap(nxt);\n  }\n  return faces;\n}'},
    {'category': '图论', 'sub': '支配树', 'name': '支配树', 'aliases': ['dominator tree', '支配'], 'intro': '有向图从源点出发，求每个点被哪些点支配；Lengauer-Tarjan 算法 O((n+m)α)。', 'complexity': 'O((n+m) α(n))', 'quality': 'complete', 'cpp': 'vector<int> domTree(int s, vector<vector<int>>& g) {\n  int n = (int)g.size();\n  vector<vector<int>> rg(n), bucket(n);\n  vector<int> dfn(n, -1), id(n), fa(n), semi(n), idom(n), dsu(n), best(n);\n  int T = 0;\n  function<void(int)> dfs = [&](int u) {\n    dfn[u] = T; id[T] = u;\n    semi[T] = dsu[T] = best[T] = T;\n    for (int v : g[u]) if (dfn[v] == -1) {\n      fa[dfn[v]] = dfn[u];\n      dfs(v);\n      rg[dfn[v]].push_back(dfn[u]);\n    }\n  };\n  dfs(s);\n  function<int(int)> find = [&](int x) -> int {\n    if (dsu[x] == x) return x;\n    int y = find(dsu[x]);\n    if (semi[best[x]] > semi[best[dsu[x]]]) best[x] = best[dsu[x]];\n    return dsu[x] = y;\n  };\n  auto eval = [&](int x) { find(x); return best[x]; };\n  for (int i = T - 1; i > 0; i--) {\n    for (int v : rg[i]) {\n      int u = eval(v);\n      if (semi[u] < semi[i]) semi[i] = semi[u];\n    }\n    bucket[semi[i]].push_back(i);\n    for (int v : bucket[i]) {\n      int u = eval(v);\n      idom[v] = (semi[u] < semi[v]) ? u : i;\n    }\n    dsu[i] = fa[i];\n  }\n  for (int i = 1; i < T; i++)\n    if (idom[i] != semi[i]) idom[i] = idom[idom[i]];\n  vector<int> ans(n, -1);\n  for (int i = 1; i < T; i++) ans[id[i]] = id[idom[i]];\n  ans[s] = s;\n  return ans;\n}'},
    {'category': '图论', 'sub': '树分治', 'name': '点分治/边分治', 'quality': 'complete', 'aliases': ['点分治', '边分治', 'centroid decomposition'], 'intro': '每次找树的重心，统计经过重心的路径，再递归子树，总复杂度 O(n log n)。', 'complexity': 'O(n log n)', 'cpp': 'int sz[N]; bool del[N];\nvoid dfsSz(int u,int f){ sz[u]=1; for(int v:g[u]) if(v!=f&&!del[v]) dfsSz(v,u), sz[u]+=sz[v]; }\nint findCen(int u,int f,int tot){\n  for(int v:g[u]) if(v!=f&&!del[v]&&sz[v]*2>tot) return findCen(v,u,tot);\n  return u;\n}\nvoid solve(int u){\n  dfsSz(u,0); int c=findCen(u,0,sz[u]);\n  // 统计所有经过 c 的路径\n  del[c]=true;\n  for(int v:g[c]) if(!del[v]) solve(v);\n}'},
    {'category': '图论', 'sub': '离线动态图', 'name': '动态图连通性（离线）', 'aliases': ['线段树分治', '动态连通性', 'offline dynamic connectivity'], 'intro': '用线段树分治把每条边的存活区间挂到线段树节点，配合可撤销并查集回答离线连通性。', 'complexity': 'O((n+q) log^2 n)', 'quality': 'complete', 'cpp': 'struct RollbackDSU {\n  vector<int> p, sz;\n  vector<tuple<int,int,int,int>> hist;\n  RollbackDSU(int n) : p(n), sz(n,1) { iota(p.begin(), p.end(), 0); }\n  int find(int x) { while (p[x] != x) x = p[x]; return x; }\n  bool unite(int a, int b) {\n    a = find(a); b = find(b);\n    if (a == b) return false;\n    if (sz[a] < sz[b]) swap(a, b);\n    hist.push_back({a, b, sz[a], sz[b]});\n    p[b] = a; sz[a] += sz[b];\n    return true;\n  }\n  void rollback() {\n    auto [a,b,sa,sb] = hist.back(); hist.pop_back();\n    p[b] = b; sz[a] = sa; sz[b] = sb;\n  }\n  bool same(int a, int b) { return find(a) == find(b); }\n};\nvector<vector<pair<int,int>>> seg;\nvoid addEdge(int node, int l, int r, int ql, int qr, int u, int v) {\n  if (ql <= l && r <= qr) { seg[node].push_back({u,v}); return; }\n  int m = (l + r) / 2;\n  if (ql <= m) addEdge(node*2, l, m, ql, qr, u, v);\n  if (qr > m) addEdge(node*2+1, m+1, r, ql, qr, u, v);\n}\nvoid solve(int node, int l, int r, RollbackDSU& dsu, vector<pair<int,int>>& query, vector<bool>& ans) {\n  int base = (int)dsu.hist.size();\n  for (auto [u,v] : seg[node]) dsu.unite(u, v);\n  if (l == r) ans[l] = dsu.same(query[l].first, query[l].second);\n  else {\n    int m = (l + r) / 2;\n    solve(node*2, l, m, dsu, query, ans);\n    solve(node*2+1, m+1, r, dsu, query, ans);\n  }\n  while ((int)dsu.hist.size() > base) dsu.rollback();\n}'},
    {'category': '动态规划', 'sub': '插头 DP', 'name': '插头 DP', 'aliases': ['plug DP', '插头dp', '轮廓线DP进阶'], 'intro': '棋盘连通性/回路计数问题：用括号序列或最小表示法表示轮廓线上的插头状态。', 'complexity': 'O(n·m·状态数)', 'quality': 'complete', 'cpp': '// 最小表示法插头 DP：state 用 vector<int> 记录每个位置所属连通块\nstruct StateHash {\n  size_t operator()(const vector<int>& s) const {\n    size_t h = 0;\n    for (int x : s) h = h * 13331 + x;\n    return h;\n  }\n};\nlong long plugDP(vector<vector<int>>& board) {\n  int n = (int)board.size(), m = (int)board[0].size();\n  unordered_map<vector<int>, long long, StateHash> dp;\n  dp[vector<int>(m + 1, 0)] = 1;\n  for (int i = 0; i < n; i++) {\n    // 换行：整体右移一位，最左补 0\n    unordered_map<vector<int>, long long, StateHash> nxt;\n    for (auto& [st, val] : dp) {\n      vector<int> ns(m + 1, 0);\n      for (int j = 0; j < m; j++) ns[j + 1] = st[j];\n      nxt[ns] += val;\n    }\n    dp.swap(nxt);\n    for (int j = 0; j < m; j++) {\n      unordered_map<vector<int>, long long, StateHash> ndp;\n      for (auto& [st, val] : dp) {\n        if (board[i][j] == 0) {\n          if (st[j] == 0 && st[j+1] == 0) ndp[st] += val;\n          continue;\n        }\n        int left = st[j], up = st[j+1];\n        if (left == 0 && up == 0) {\n          if (j + 1 < m && i + 1 < n) {\n            auto ns = st; ns[j] = ns[j+1] = 7; // 新连通块编号，实际应做最小表示\n            ndp[ns] += val;\n          }\n        } else if (left == 0 || up == 0) {\n          int id = left ? left : up;\n          if (j + 1 < m) { auto ns = st; ns[j] = id; ns[j+1] = 0; ndp[ns] += val; }\n          if (i + 1 < n) { auto ns = st; ns[j] = 0; ns[j+1] = id; ndp[ns] += val; }\n        } else if (left == up) {\n          auto ns = st; ns[j] = ns[j+1] = 0; ndp[ns] += val; // 闭合一个连通块\n        } else {\n          auto ns = st; ns[j] = ns[j+1] = 0;\n          for (int k = 0; k <= m; k++) if (ns[k] == up) ns[k] = left;\n          ndp[ns] += val;\n        }\n      }\n      dp.swap(ndp);\n    }\n  }\n  return dp[vector<int>(m + 1, 0)];\n}'},
    {'category': '动态规划', 'sub': 'DP 套 DP', 'name': 'DP 套 DP', 'aliases': ['DP of DP', '自动机DP'], 'intro': '把内层 DP 的转移表/结果作为外层 DP 的状态，常用于计数满足某 DP 性质的串/方案。', 'complexity': '视内层状态数而定', 'quality': 'complete', 'cpp': 'const int MOD = 998244353;\n// 例：统计长度为 n 的 0/1 串中，LIS 长度恰好为 k 的方案数。\n// 内层：LIS 的 tail 数组 g；外层：g 作为状态，枚举下一个字符转移。\nint countLISStrings(int n, int k) {\n  map<vector<int>, int> dp;\n  dp[{}] = 1;\n  for (int pos = 0; pos < n; pos++) {\n    map<vector<int>, int> ndp;\n    for (auto& [g, val] : dp) {\n      for (int c = 0; c <= 1; c++) {\n        vector<int> ng = g;\n        auto it = lower_bound(ng.begin(), ng.end(), c);\n        if (it == ng.end()) {\n          if ((int)ng.size() < k) ng.push_back(c);\n          else continue;\n        } else {\n          *it = c;\n        }\n        ndp[ng] = (ndp[ng] + val) % MOD;\n      }\n    }\n    dp.swap(ndp);\n  }\n  int ans = 0;\n  for (auto& [g, val] : dp) if ((int)g.size() == k) ans = (ans + val) % MOD;\n  return ans;\n}'},
    {'category': '动态规划', 'sub': '分治 DP', 'name': '分治 DP', 'quality': 'complete', 'aliases': ['divide and conquer DP', '决策单调分治'], 'intro': '当 dp 转移满足决策单调性时，用分治确定最优决策点，复杂度 O(n log n·calc)。', 'complexity': 'O(n log n · cost)', 'cpp': 'void solve(int l,int r,int optL,int optR){\n  if(l>r) return;\n  int mid=(l+r)/2, best=optL;\n  long long bestVal=INF;\n  for(int k=optL;k<=min(mid-1,optR);k++){\n    long long val=dp[k]+cost(k,mid);\n    if(val<bestVal) bestVal=val, best=k;\n  }\n  dp[mid]=bestVal;\n  solve(l,mid-1,optL,best);\n  solve(mid+1,r,best,optR);\n}'},
    {'category': '网络流', 'sub': '上下界网络流', 'name': '上下界网络流', 'aliases': ['上下界可行流', '有源汇上下界', 'bounded flow'], 'intro': '把每条边的下界先流满，再建超级源汇跑附加网络判断可行流/最大流。', 'complexity': 'O(maxflow)', 'quality': 'complete', 'cpp': 'struct Dinic {\n  struct Edge { int to, cap, rev; };\n  vector<vector<Edge>> g;\n  vector<int> level, it;\n  Dinic(int n) : g(n), level(n), it(n) {}\n  void addEdge(int u, int v, int cap) {\n    g[u].push_back({v, cap, (int)g[v].size()});\n    g[v].push_back({u, 0, (int)g[u].size()-1});\n  }\n  bool bfs(int s, int t) {\n    fill(level.begin(), level.end(), -1);\n    queue<int> q; q.push(s); level[s] = 0;\n    while (!q.empty()) {\n      int u = q.front(); q.pop();\n      for (auto& e : g[u]) if (e.cap > 0 && level[e.to] < 0) {\n        level[e.to] = level[u] + 1;\n        q.push(e.to);\n      }\n    }\n    return level[t] >= 0;\n  }\n  int dfs(int u, int t, int f) {\n    if (u == t) return f;\n    for (int& i = it[u]; i < (int)g[u].size(); i++) {\n      Edge& e = g[u][i];\n      if (e.cap > 0 && level[e.to] == level[u] + 1) {\n        int ret = dfs(e.to, t, min(f, e.cap));\n        if (ret > 0) {\n          e.cap -= ret;\n          g[e.to][e.rev].cap += ret;\n          return ret;\n        }\n      }\n    }\n    return 0;\n  }\n  int maxFlow(int s, int t) {\n    int flow = 0;\n    while (bfs(s, t)) {\n      fill(it.begin(), it.end(), 0);\n      while (int f = dfs(s, t, 1e9)) flow += f;\n    }\n    return flow;\n  }\n};\n// 有源汇上下界最大流：\n// 1. 对每条 u->v 容量 [lo,hi]，加边 u->v 容量 hi-lo，并维护 in[v]+=lo, in[u]-=lo。\n// 2. 建超级源 SS、超级汇 TT；in>0 时 SS->i 加 in，in<0 时 i->TT 加 -in。\n// 3. 先跑 SS->TT 判断是否满流（满流才有可行流）。\n// 4. 原汇 t -> 原源 s 加 INF 边后，再跑 s->t 得到最大流。'},
    {'category': '网络流', 'sub': '费用流', 'name': '最小费用最大流', 'quality': 'complete', 'aliases': ['MCMF', '费用流', 'min cost max flow'], 'intro': '每次用 SPFA/Dijkstra 找单位费用最短的增广路并增广，累加费用。', 'complexity': 'O(F·E log V)', 'cpp': 'struct MCMF {\n  struct Edge { int to, cap, cost, rev; };\n  vector<vector<Edge>> g;\n  void addEdge(int u,int v,int cap,int cost){\n    g[u].push_back({v,cap,cost,(int)g[v].size()});\n    g[v].push_back({u,0,-cost,(int)g[u].size()-1});\n  }\n  pair<int,int> minCostMaxFlow(int s,int t){\n    int flow=0,cost=0;\n    const int INF=1e9;\n    while(true){\n      vector<int> dist(g.size(),INF), pv(g.size()), pe(g.size());\n      vector<bool> inq(g.size());\n      queue<int> q; q.push(s); dist[s]=0; inq[s]=true;\n      while(!q.empty()){\n        int u=q.front(); q.pop(); inq[u]=false;\n        for(int i=0;i<(int)g[u].size();i++){\n          Edge& e=g[u][i];\n          if(e.cap>0 && dist[e.to]>dist[u]+e.cost){\n            dist[e.to]=dist[u]+e.cost; pv[e.to]=u; pe[e.to]=i;\n            if(!inq[e.to]){ inq[e.to]=true; q.push(e.to); }\n          }\n        }\n      }\n      if(dist[t]==INF) break;\n      int add=INF;\n      for(int v=t;v!=s;v=pv[v]) add=min(add,g[pv[v]][pe[v]].cap);\n      for(int v=t;v!=s;v=pv[v]){\n        Edge& e=g[pv[v]][pe[v]];\n        e.cap-=add; g[v][e.rev].cap+=add;\n      }\n      flow+=add; cost+=add*dist[t];\n    }\n    return {flow,cost};\n  }\n};'},
]

for _algorithm in ALGORITHMS:
    _algorithm['info'] = get_alg_info(_algorithm['name'])

ALGORITHM_COUNT = 120


ALGORITHM_BY_NAME = {a["name"]: a for a in ALGORITHMS}
