"""算法注册表：120 个算法名称 + 信息论标签（轻量名称索引）。

算法之间的概率关系在 feature_algorithm_matrix.json；
信息论标签在 info_framework.py，统一由本注册表挂载。
"""

from typing import Any

from info_framework import get_alg_info

ALGORITHM_NAMES = [
    "暴力枚举",
    "约瑟夫环（模拟）",
    "区间调度（贪心）",
    "排序后取最值（基础贪心）",
    "反悔贪心（带堆维护）",
    "二分查找",
    "二分答案",
    "归并排序求逆序对",
    "结构体排序（重载运算符）",
    "一维前缀和",
    "二维前缀和",
    "差分数组",
    "双指针（滑动窗口）",
    "构造算法",
    "位掩码子集枚举",
    "状态压缩 + BFS",
    "单调栈",
    "栈（基础）",
    "单调队列（滑动窗口）",
    "队列（基础）",
    "堆（Top-K）",
    "并查集 (DSU)",
    "带权并查集",
    "线段树（区间和 + 懒标记）",
    "ST 表（静态区间最值）",
    "树状数组 (BIT)",
    "树状数组求逆序对",
    "FHQ Treap（无旋 Treap）",
    "线段树合并/分裂",
    "可撤销并查集",
    "Dijkstra",
    "Bellman-Ford",
    "Floyd-Warshall",
    "Kruskal",
    "Prim",
    "Dinic 最大流",
    "最小割建模",
    "Tarjan 求 SCC",
    "拓扑排序 (Kahn)",
    "连通块染色",
    "二分图染色判定",
    "简单回溯",
    "割点 / 桥",
    "拓扑排序 + DAG DP",
    "二分图最大匹配（匈牙利）",
    "KM 算法",
    "2-SAT",
    "LCA（倍增）",
    "树上差分",
    "树的直径 / 重心",
    "基环树 DP",
    "仙人掌 / 圆方树",
    "LIS（最长上升子序列）",
    "LCS（最长公共子序列）",
    "0/1 背包",
    "完全背包",
    "石子合并",
    "树上最大权独立集",
    "TSP（状压）",
    "数位 DP（不含 4）",
    "斜率优化（CHT）",
    "四边形不等式优化",
    "轮廓线 DP（简单棋盘状压）",
    "KMP",
    "Z-function",
    "AC 自动机",
    "AC 自动机 + 矩阵快速幂",
    "后缀数组 (SA)",
    "Manacher",
    "SAM（后缀自动机）",
    "Trie（字典树）",
    "字符串哈希（Rolling Hash）",
    "线性筛（欧拉筛）",
    "埃氏筛",
    "素数判定（试除法）",
    "欧拉函数",
    "快速幂",
    "扩展欧几里得 (exgcd)",
    "费马小定理求逆元",
    "组合数（预处理阶乘）",
    "中国剩余定理 (CRT)",
    "Lucas 定理",
    "容斥原理",
    "错排 / 卡特兰数",
    "唯一分解定理",
    "高斯消元（异或方程组 bitset）",
    "扩展中国剩余定理（EXCRT）",
    "线性基",
    "GCD / LCM",
    "矩阵快速幂优化递推",
    "Andrew 单调链凸包",
    "旋转卡壳",
    "最近点对（分治）",
    "线段相交判定",
    "叉积 / 点积判断方位",
    "Nim 游戏与 SG 函数",
    "期望 DP（掷骰子）",
    "莫队（区间不同数）",
    "主席树（区间第 k 小）",
    "Link-Cut Tree (LCT)",
    "树链剖分 (HLD)",
    "可持久化数据结构（主席树进阶）",
    "后缀自动机（SAM）进阶",
    "广义 SAM",
    "FFT",
    "NTT",
    "生成函数",
    "莫比乌斯反演",
    "线性基进阶",
    "半平面交",
    "最小圆覆盖",
    "三维凸包",
    "支配树",
    "点分治/边分治",
    "动态图连通性（离线）",
    "插头 DP",
    "DP 套 DP",
    "分治 DP",
    "上下界网络流",
    "最小费用最大流"
]

ALGORITHMS: list[dict[str, Any]] = [{"name": name} for name in ALGORITHM_NAMES]
for _algorithm in ALGORITHMS:
    _algorithm["info"] = get_alg_info(_algorithm["name"])

ALGORITHM_COUNT = len(ALGORITHMS)
ALGORITHM_BY_NAME = {a["name"]: a for a in ALGORITHMS}

