# -*- coding: utf-8 -*-
"""Codeforces 难度阶梯 · 8 档知识树数据。"""

from tier8_thoughts import TIER8_THOUGHTS

TIERS = [
    {
        "id": 1,
        "name": "第 1 档",
        "range": "1200 – 1400",
        "color": "#9A928A",
        "goal": "核心训练：代码实现力",
        "phase": 1,
        "phase_name": "阶段一：线性结构 & 数值熵",
        "tags": [
            {
                "id": "brute-force",
                "name": "暴力枚举",
                "cf_tag": "brute force",
                "desc": "嵌套循环、位掩码子集枚举",
                "algorithms": ["暴力枚举", "位掩码子集枚举"],
            },
            {
                "id": "sortings",
                "name": "排序",
                "cf_tag": "sortings",
                "desc": "重载运算符 / 结构体排序",
                "algorithms": ["结构体排序（重载运算符）", "归并排序求逆序对"],
            },
            {
                "id": "greedy",
                "name": "基础贪心",
                "cf_tag": "greedy",
                "desc": "排序后取最值",
                "algorithms": ["排序后取最值（基础贪心）", "区间调度（贪心）"],
            },
            {
                "id": "binary-search",
                "name": "二分答案",
                "cf_tag": "binary search",
                "desc": "整数域简单 check",
                "algorithms": ["二分答案", "二分查找"],
            },
            {
                "id": "math-basic",
                "name": "基础数学",
                "cf_tag": "math",
                "desc": "GCD/LCM、素数判定、埃氏筛、快速幂",
                "algorithms": ["GCD / LCM", "素数判定（试除法）", "埃氏筛", "快速幂"],
            },
            {
                "id": "implementation",
                "name": "纯模拟",
                "cf_tag": "implementation",
                "desc": "按题意复现流程",
                "algorithms": ["约瑟夫环（模拟）"],
            },
        ],
    },
    {
        "id": 2,
        "name": "第 2 档",
        "range": "1400 – 1600",
        "color": "#8B9A6B",
        "goal": "核心训练：思维转换力",
        "phase": 1,
        "phase_name": "阶段一：线性结构 & 数值熵",
        "tags": [
            {
                "id": "two-pointers",
                "name": "双指针",
                "cf_tag": "two pointers",
                "desc": "双指针 / 滑动窗口维护区间性质",
                "algorithms": ["双指针（滑动窗口）"],
            },
            {
                "id": "prefix-sum",
                "name": "前缀和与差分",
                "cf_tag": None,
                "desc": "一维/二维前缀和与差分数组",
                "algorithms": ["一维前缀和", "二维前缀和", "差分数组"],
            },
            {
                "id": "constructive",
                "name": "构造",
                "cf_tag": "constructive algorithms",
                "desc": "奇偶性/模运算构造解",
                "algorithms": ["构造算法"],
            },
            {
                "id": "sortings-greedy",
                "name": "排序 + 贪心",
                "cf_tag": "greedy",
                "desc": "排序后带反悔/优先队列贪心",
                "algorithms": ["反悔贪心（带堆维护）", "排序后取最值（基础贪心）"],
            },
            {
                "id": "number-theory",
                "name": "数论",
                "cf_tag": "number theory",
                "desc": "唯一分解定理、欧拉筛、逆元·费马小定理",
                "algorithms": ["唯一分解定理", "线性筛（欧拉筛）", "费马小定理求逆元", "欧拉函数", "扩展欧几里得 (exgcd)"],
            },
            {
                "id": "dp-basic",
                "name": "动态规划（限定）",
                "cf_tag": "dp",
                "desc": "0/1 背包、完全背包、LIS 的 O(n log n)",
                "algorithms": ["0/1 背包", "完全背包", "LIS（最长上升子序列）", "LCS（最长公共子序列）"],
            },
            {
                "id": "ds-basic",
                "name": "数据结构（限定）",
                "cf_tag": "data structures",
                "desc": "栈、队列、单调栈、单调队列",
                "algorithms": ["栈（基础）", "队列（基础）", "单调栈", "单调队列（滑动窗口）", "堆（Top-K）"],
            },
        ],
    },
    {
        "id": 3,
        "name": "第 3 档",
        "range": "1600 – 1800",
        "color": "#6B8FA3",
        "goal": "核心训练：板子背诵力（当前所在档位）",
        "phase": 2,
        "phase_name": "阶段二：拓扑传播 & 依赖熵",
        "tags": [
            {
                "id": "graphs-basic",
                "name": "图论（基础）",
                "cf_tag": "graphs",
                "desc": "Dijkstra、Bellman-Ford、Floyd、Kruskal/Prim",
                "algorithms": ["Dijkstra", "Bellman-Ford", "Floyd-Warshall", "Kruskal", "Prim"],
            },
            {
                "id": "dfs-similar",
                "name": "DFS / BFS",
                "cf_tag": "dfs and similar",
                "desc": "连通块染色、二分图染色判定、简单回溯",
                "algorithms": ["连通块染色", "二分图染色判定", "简单回溯"],
            },
            {
                "id": "dp-advanced",
                "name": "动态规划（进阶）",
                "cf_tag": "dp",
                "desc": "区间 DP（石子合并）、状压 DP（n≤20 TSP）、树形 DP（最大独立集）",
                "algorithms": ["石子合并", "TSP（状压）", "树上最大权独立集"],
            },
            {
                "id": "strings-basic",
                "name": "字符串（基础）",
                "cf_tag": "strings",
                "desc": "KMP（Next 数组）、Trie（字典树插入/查询）",
                "algorithms": ["KMP", "Trie（字典树）", "字符串哈希（Rolling Hash）"],
            },
            {
                "id": "dsu",
                "name": "并查集",
                "cf_tag": "dsu",
                "desc": "路径压缩 + 按秩合并，带权并查集维护到根距离",
                "algorithms": ["并查集 (DSU)", "带权并查集"],
            },
            {
                "id": "bitmasks",
                "name": "位运算",
                "cf_tag": "bitmasks",
                "desc": "位运算枚举子集、状态压缩配合 BFS",
                "algorithms": ["位掩码子集枚举", "状态压缩 + BFS"],
            },
            {
                "id": "matrices",
                "name": "矩阵",
                "cf_tag": "matrices",
                "desc": "矩阵快速幂优化递推",
                "algorithms": ["矩阵快速幂优化递推"],
            },
        ],
    },
    {
        "id": 4,
        "name": "第 4 档",
        "range": "1800 – 2000",
        "color": "#9A6B8B",
        "goal": "核心训练：组合缝合力",
        "phase": 2,
        "phase_name": "阶段二：拓扑传播 & 依赖熵",
        "tags": [
            {
                "id": "trees",
                "name": "树（必会）",
                "cf_tag": "trees",
                "desc": "LCA（倍增/树链剖分）、树上差分（点/边）、树的直径/重心",
                "algorithms": ["LCA（倍增）", "树上差分", "树的直径 / 重心"],
            },
            {
                "id": "ds-advanced",
                "name": "数据结构（进阶）",
                "cf_tag": "data structures",
                "desc": "线段树（区间加/求和 + 懒标记）、树状数组（逆序对/动态前缀和）",
                "algorithms": ["线段树（区间和 + 懒标记）", "树状数组 (BIT)", "树状数组求逆序对", "ST 表（静态区间最值）"],
            },
            {
                "id": "graphs-advanced",
                "name": "图论（进阶）",
                "cf_tag": "graphs",
                "desc": "Tarjan（SCC 缩点变 DAG）、割点/桥、拓扑排序 + DP 跑 DAG 最长路",
                "algorithms": ["Tarjan 求 SCC", "割点 / 桥", "拓扑排序 (Kahn)", "拓扑排序 + DAG DP"],
            },
            {
                "id": "combinatorics",
                "name": "组合数学",
                "cf_tag": "combinatorics",
                "desc": "卢卡斯 Lucas、容斥原理（基础）、错排/卡特兰数",
                "algorithms": ["Lucas 定理", "容斥原理", "错排 / 卡特兰数", "组合数（预处理阶乘）"],
            },
            {
                "id": "game-theory",
                "name": "博弈论",
                "cf_tag": "games",
                "desc": "SG 函数打表找规律、Nim 和变种",
                "algorithms": ["Nim 游戏与 SG 函数"],
            },
            {
                "id": "string-suffix-edge",
                "name": "后缀结构（边缘）",
                "cf_tag": "string suffix structures",
                "desc": "Manacher（回文半径）、Z-function（扩展 KMP）",
                "algorithms": ["Manacher", "Z-function", "后缀数组 (SA)"],
            },
            {
                "id": "dp-edge",
                "name": "动态规划（边缘）",
                "cf_tag": "dp",
                "desc": "数位 DP（记忆化搜索）、轮廓线 DP（简单棋盘状压）",
                "algorithms": ["数位 DP（不含 4）", "轮廓线 DP（简单棋盘状压）", "期望 DP（掷骰子）"],
            },
        ],
    },
    {
        "id": 5,
        "name": "第 5 档",
        "range": "2000 – 2200",
        "color": "#C25E5E",
        "goal": "核心训练：建模抽象力",
        "phase": 3,
        "phase_name": "阶段三：决策容量 & 剪枝熵",
        "tags": [
            {
                "id": "flows-basic",
                "name": "网络流（入门）",
                "cf_tag": "flows",
                "desc": "Dinic 最大流板子，建图：二分图最大匹配转最大流、点拆分成入点出点",
                "algorithms": ["Dinic 最大流", "最小割建模"],
            },
            {
                "id": "graph-matchings",
                "name": "图匹配",
                "cf_tag": "graph matchings",
                "desc": "匈牙利算法（增广路）、KM 算法（O(n³) 板子）",
                "algorithms": ["二分图最大匹配（匈牙利）", "KM 算法"],
            },
            {
                "id": "ds-senior",
                "name": "数据结构（高级）",
                "cf_tag": "data structures",
                "desc": "主席树（静态区间第 K 小）、FHQ Treap（序列翻转/插入/删除）",
                "algorithms": ["主席树（区间第 k 小）", "FHQ Treap（无旋 Treap）", "莫队（区间不同数）"],
            },
            {
                "id": "dp-optimize",
                "name": "动态规划（高级优化）",
                "cf_tag": "dp",
                "desc": "斜率优化（CHT，转移含 i·j 项）、四边形不等式优化（区间 DP 决策单调）",
                "algorithms": ["斜率优化（CHT）", "四边形不等式优化"],
            },
            {
                "id": "geometry",
                "name": "计算几何",
                "cf_tag": "geometry",
                "desc": "Andrew 凸包（求凸壳）、叉积/点积判断方位",
                "algorithms": ["Andrew 单调链凸包", "叉积 / 点积判断方位", "最近点对（分治）", "线段相交判定"],
            },
            {
                "id": "math-advanced",
                "name": "数学（进阶）",
                "cf_tag": "math",
                "desc": "高斯消元（异或方程组 bitset 优化）、EXCRT、线性基（异或最大/第 K 小）",
                "algorithms": ["高斯消元（异或方程组 bitset）", "扩展中国剩余定理（EXCRT）", "线性基", "中国剩余定理 (CRT)"],
            },
            {
                "id": "string-suffix-adv",
                "name": "后缀结构（进阶）",
                "cf_tag": "string suffix structures",
                "desc": "AC 自动机 + 矩阵快速幂（统计不包含模式串的方案数）",
                "algorithms": ["AC 自动机 + 矩阵快速幂", "AC 自动机"],
            },
        ],
    },
    {
        "id": 6,
        "name": "第 6 档",
        "range": "2200 – 2400",
        "color": "#C79A6B",
        "goal": "核心训练：直觉与避错",
        "phase": 3,
        "phase_name": "阶段三：决策容量 & 剪枝熵",
        "tags": [
            {
                "id": "flows-core",
                "name": "网络流（核心难点）",
                "cf_tag": "flows",
                "desc": "最小割建模（最大权闭合子图、二分图最小点覆盖/最大独立集），建图逻辑极其抽象",
                "algorithms": ["最小割建模"],
            },
            {
                "id": "2-sat",
                "name": "2-SAT",
                "cf_tag": "2-sat",
                "desc": "建边逻辑（蕴含式），Tarjan 缩点判解 / 拓扑排序构造方案",
                "algorithms": ["2-SAT"],
            },
            {
                "id": "ds-stitch",
                "name": "数据结构（缝合）",
                "cf_tag": "data structures",
                "desc": "线段树合并/分裂（树上颜色计数 / 区间排序）、可撤销并查集（按秩合并 + 栈回滚，配合线段树分治）",
                "algorithms": ["线段树合并/分裂", "可撤销并查集"],
            },
            {
                "id": "matroids-greedy",
                "name": "反悔贪心",
                "cf_tag": "greedy",
                "desc": "带堆维护的反悔自动机，如可反悔的后悔堆",
                "algorithms": ["反悔贪心（带堆维护）"],
            },
            {
                "id": "trees-advanced",
                "name": "树（进阶）",
                "cf_tag": "trees",
                "desc": "基环树 DP（断环成链 + 两次树形 DP）、仙人掌图（圆方树静态入门，只建图跑 DP，不维护动态）",
                "algorithms": ["基环树 DP", "仙人掌 / 圆方树"],
            },
            {
                "id": "geometry-advanced",
                "name": "计算几何（进阶）",
                "cf_tag": "geometry",
                "desc": "旋转卡壳（凸包直径/最远点对/最小矩形覆盖）",
                "algorithms": ["旋转卡壳"],
            },
            {
                "id": "sam",
                "name": "SAM（后缀自动机）",
                "cf_tag": "string suffix structures",
                "desc": "只学建图和求本质不同子串个数，及两个串的 LCS（最长公共子串）",
                "algorithms": ["SAM（后缀自动机）"],
            },
        ],
    },
    {
        "id": 7,
        "name": "第 7 档",
        "range": "2400 – 2800",
        "color": "#A94442",
        "goal": "核心训练：深度融合力",
        "phase": 4,
        "phase_name": "阶段四：时空变换 & 纠缠熵",
        "tags": [
            {
                "id": "ds-ultimate",
                "name": "数据结构（究极体）",
                "cf_tag": "data structures",
                "desc": "Link-Cut Tree（LCT）、树链剖分（HLD）进阶、可持久化数据结构（主席树进阶）、线段树合并/分裂（高级应用）",
                "algorithms": ["Link-Cut Tree (LCT)", "树链剖分 (HLD)", "可持久化数据结构（主席树进阶）", "线段树合并/分裂", "主席树（区间第 k 小）"],
            },
            {
                "id": "string-ultimate",
                "name": "字符串（究极体）",
                "cf_tag": "string suffix structures",
                "desc": "后缀数组（SA）、后缀自动机（SAM）进阶、广义 SAM",
                "algorithms": ["后缀数组 (SA)", "后缀自动机（SAM）进阶", "广义 SAM", "SAM（后缀自动机）"],
            },
            {
                "id": "math-ultimate",
                "name": "数学（究极体）",
                "cf_tag": "math",
                "desc": "快速傅里叶变换（FFT）、快速数论变换（NTT）、生成函数、莫比乌斯反演、线性基进阶",
                "algorithms": ["FFT", "NTT", "生成函数", "莫比乌斯反演", "线性基进阶", "线性基"],
            },
            {
                "id": "geometry-ultimate",
                "name": "计算几何（进阶）",
                "cf_tag": "geometry",
                "desc": "半平面交、最小圆覆盖、三维凸包",
                "algorithms": ["半平面交", "最小圆覆盖", "三维凸包"],
            },
            {
                "id": "graph-ultimate",
                "name": "高级图论",
                "cf_tag": "graphs",
                "desc": "支配树、点分治/边分治、动态图连通性（离线）、仙人掌圆方树（动态维护）",
                "algorithms": ["支配树", "点分治/边分治", "动态图连通性（离线）", "仙人掌 / 圆方树"],
            },
            {
                "id": "dp-ultimate",
                "name": "复杂 DP",
                "cf_tag": "dp",
                "desc": "插头 DP（轮廓线进阶）、DP 套 DP、分治 DP、斜率优化（CHT）进阶",
                "algorithms": ["插头 DP", "DP 套 DP", "分治 DP", "斜率优化（CHT）", "轮廓线 DP（简单棋盘状压）"],
            },
            {
                "id": "flow-ultimate",
                "name": "高级网络流",
                "cf_tag": "flows",
                "desc": "上下界网络流、最小费用最大流",
                "algorithms": ["上下界网络流", "最小费用最大流"],
            },
        ],
    },
    {
        "id": 8,
        "name": "第 8 档",
        "range": "2800 – 3500+",
        "color": "#3E2723",
        "goal": "核心训练：创造性思维",
        "phase": 4,
        "phase_name": "阶段四：时空变换 & 纠缠熵",
        "tags": [
            {
                "id": "insight",
                "name": "洞察最优解本质",
                "group": "核心思维",
                "cf_tag": None,
                "desc": "从题目条件中直接看穿关键性质，避免被表层复杂度误导。常见突破口：观察答案的单调性/对称性/极值位置，先猜后证，用反例修正直觉。",
                "detail": "严谨表达：从条件中直接提取关键性质（单调性、对称性、极值位置），把注意力从“怎么算”转移到“什么是本质”。\n\n通俗化解释：先猜后证，用反例修正直觉；不是枚举所有方案，而是先看“答案必须长什么样”。\n\n使用提示：80% 的 2800+ 题，关键观察写在读题前 5 分钟。",
                "algorithms": [],
            },
            {
                "id": "criterion",
                "name": "寻找充要条件",
                "group": "核心思维",
                "cf_tag": None,
                "desc": "把可行解的存在性/最优性转化为可验证的充要条件。常见手法：把“能否做到”变成“某个不等式/奇偶性/模数条件是否成立”，再构造证明。",
                "detail": "严谨表达：把可行解存在性/最优性等价为可验证条件，如不等式、奇偶性、模数条件。\n\n通俗化解释：“能不能做到”不要直接试，先找一个“非如此不可”的判据；充要条件一旦找到，构造自然浮现。\n\n使用提示：先证必要性再证充分性，缺一不可。",
                "algorithms": [],
            },
            {
                "id": "subtask",
                "name": "子任务泛化",
                "group": "核心思维",
                "cf_tag": None,
                "desc": "先解决子任务或弱化版，再推广到原问题。常见手法：先做 n 小、值域小、无限制的版本，找出规律后再处理一般情况；也常用于 DP 状态设计。",
                "detail": "严谨表达：先解决子任务或弱化版，在受限版本中找到规律，再推广到一般情况。\n\n通俗化解释：从 n 小、值域小、无限制、无修改的版本入手，让规律先露头；很多 DP 状态就是这样设计的。\n\n使用提示：弱化版不是浪费时间，是给原题画地图。",
                "algorithms": [],
            },
            {
                "id": "fix-variable",
                "name": "固定变量优化",
                "group": "核心思维",
                "cf_tag": None,
                "desc": "枚举/固定一个变量后，剩余问题变成可快速求解的形式。常见手法：固定左端点/右端点/中位数/某个下标，用数据结构维护另一维的最优值。",
                "detail": "严谨表达：枚举/固定一个变量后，剩余问题变成可快速求解的形式，用数据结构维护另一维最优值。\n\n通俗化解释：把二维困难拆成一维循环 + 一维维护；固定谁，取决于谁的变化对答案影响最简洁。\n\n使用提示：常与单调栈、线段树、滑动窗口配合。",
                "algorithms": [],
            },
            {
                "id": "bounds",
                "name": "构造上下界",
                "group": "核心思维",
                "cf_tag": None,
                "desc": "先证明答案上下界，再构造达到该界的方案。常见手法：用鸽巢/平均/最大最小给出下界，再用显式构造证明可达，避免只猜不证。",
                "detail": "严谨表达：先证明答案上下界，再构造达到该界的方案。\n\n通俗化解释：用鸽巢/平均/最大最小给出“不可能更好”的下界，用显式构造证明“确实能达到”，避免只猜不证。\n\n使用提示：2800+ 构造题最稳的证明流程：下界 + 构造 = 最优。",
                "algorithms": [],
            },
            {
                "id": "reformulate",
                "name": "问题重表述",
                "group": "核心思维",
                "cf_tag": None,
                "desc": "把原问题等价转化为更熟悉的模型（图、代数、计数等）。常见手法：区间变图论、序列变括号序列、计数变生成函数、最值变二分判定。",
                "detail": "严谨表达：把原问题等价转化为更熟悉的模型（图、代数、计数等）。\n\n通俗化解释：区间变图论、序列变括号序列、计数变生成函数、最值变二分判定；转换后原题的复杂约束常常自动消失。\n\n使用提示：多问“这个模型还有没有另一种表示？”",
                "algorithms": [],
            },
            *TIER8_THOUGHTS,
        ],
    },
]
